### ISSUE TITLE
Error "No datadatapoints found" 

### ISSUE THREAD

**Issue by j0k3r2k17** [justwatchcom/elasticsearch_exporter#106]
I'm having an error , i open http://domain.com:9108/metrics so is full of metrics but when i open http://prometheusserver.com:9090 show metrics in graph so "No datadatapoints found"

**Comment by dominikschulz** [comment]
Did you setup prometheus to scrape the exporter?

**Comment by j0k3r2k17** [comment]
Of course, this is my configuration file : 
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'node'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['192.168.10.10:9100']
      - targets: ['192.168.10.11:9100']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['192.168.10.11:9108']

**Comment by j0k3r2k17** [comment]
i use elasticsearch version 5.5 , Don't know if this is a problem

**Comment by j0k3r2k17** [comment]
I discovered the reason, it was due to the error , LOL
