### ISSUE TITLE
Document default values.

### ISSUE THREAD

**Issue by burton-scalefastr** [justwatchcom/elasticsearch_exporter#114]
The default values aren't documented

For example.. what's the default for --es.all ?  true or false?

**Comment by zwopir** [comment]
Hi,

it's a boolean flag. If you don't specify it, it's false. If you do, it's true. Will document it.

Leaving this issue open in the meantime

**Comment by burton-scalefastr** [comment]
Right. I just don't know what the default is when not specified.

I assume false?

**Comment by zwopir** [comment]
You're right. If not specified, it's false
