### ISSUE TITLE
Inability to differentiate between red and yellow.

### ISSUE THREAD

**Issue by burton-scalefastr** [justwatchcom/elasticsearch_exporter#121]
According to this ticket:

https://github.com/justwatchcom/elasticsearch_exporter/issues/120

There is now way to detect if a cluster is red or yellow.

For dashboards like Grafana we need to show the proper color.

It looks like older versions of the plugin used 1,2,3 because the dashboards that reference this plugin on Grafana.com no longer work.  

We don't mind publishing our dashboards for Prom 2.0 and the latest elasticsearch_exporter but we have no way to differentiate between  yellow and red.

**Comment by zwopir** [comment]
sure there is way to reproduce the old behaviour:
```
(sum(elasticsearch_cluster_health_status{color="green"})*2)+sum(elasticsearch_cluster_health_status{color="yellow"})
```
this evaluates to 2 for green, 1 for yellow and 0 for red.

Hope this helps
