### ISSUE TITLE
Unassigned Shards count not showing

### ISSUE THREAD

**Issue by sba30** [justwatchcom/elasticsearch_exporter#124]
When we do the following curl command we see a difference in unassigned shard count and a difference between `number_of_nodes` vs `number_of_data_nodes` in prometheus. in prometheus it show unassigned_shards = 0 
Nodes = 75
Data_Nodes = 75

```
$ curl http://x.x.x.x.x.x:9200/_cluster/health | jq .
{
  "cluster_name": "logsearch",
  "status": "yellow",
  "timed_out": false,
  "number_of_nodes": 104,
  "number_of_data_nodes": 75,
  "active_primary_shards": 561,
  "active_shards": 1120,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 2,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 99.8217468805704
}```

**Comment by zwopir** [comment]
there is a duplicate entry of `number_of_data_nodes` in the jq output. Can you correct it. One of the entries should be `number_of_nodes`. To further analyse the issue, could you please provide me with the output of the elasticsearch_exporter /metrics endpoint? The exporter internal metrics are not required, so the output of
```
curl localhost:9108/metrics | grep -v process | grep -v go | grep -v http
``` 
as a gist would be very helpful.

**Comment by sba30** [comment]
https://gist.github.com/sba30/93558248f8788c481f3d47c83fc671a4

**Comment by sba30** [comment]
@zwopir any update on this? Can I provide you with any other info which will help?

**Comment by sba30** [comment]
Hey @zwopir do you need me to send anything else?

**Comment by zwopir** [comment]
Hey @sba30 ,

you could send me some time to further look at it. Jokes aside: I'm too busy until next week to have a look at it, but then I will have a look at the issue again. I'm very sorry about the delay!

**Comment by sba30** [comment]
Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sba30** [comment]
Hi @zwopir this was an issue with the Grafana dashboard, we have made a pull request to fix. Sorry for the bother.
