### ISSUE TITLE
Ignore certificate check

### ISSUE THREAD

**Issue by paulobezerr** [justwatchcom/elasticsearch_exporter#127]
It would be great to ignore certificates for test environments.
something like:

```bash
elasticsearch_exporter -es.cert-check false
```

**Comment by zwopir** [comment]
Hi @paulobezerr ,

sure. See #128 . Once it's merged, can you test it? I don't have an Elasticsearch at hand where I need to skip ssl-verification.

**Comment by paulobezerr** [comment]
I'll test it! Thank you very much!

**Comment by zwopir** [comment]
closed via #137
