### ISSUE TITLE
ssl-skip-verify flag is not recognised

### ISSUE THREAD

**Issue by carlosjgp** [justwatchcom/elasticsearch_exporter#130]
when running the container with the flag
```
docker run -p 9108:9108 --rm justwatch/elasticsearch_exporter:1.0.2 -es.uri=https://localhost:2006 -es.all=true -es.ssl-skip-verify=true
flag provided but not defined: -es.ssl-skip-verify
...
```
where `https://localhost:2006` is an ssh tunnel creted locally to AWS ES 6.0 endpoint (https) 

when running without the flag, the container reports
```
level=warn ts=2018-03-06T14:19:08.082340402Z caller=nodes.go:1359 msg="failed to fetch and decode node stats" err="failed to get cluster health from https://localhost:2006/_nodes/stats: Get https://localhost:2006/_nodes/stats: dial tcp 127.0.0.1:2006: getsockopt: connection refused"
```
This is the output of the exporter
https://gist.github.com/carlosjgp/2e1cbe63ef02b55770c679678bf0e313

I have checked that I can curl that endpoint skipping ssl verification
`curl -k https://localhost:2006/_nodes/stats`

**Comment by zwopir** [comment]
Hi @carlosjgp ,

which version are you running? The parameter is not yet released in a pre-build binary, so you have run the latest master

**Comment by carlosjgp** [comment]
Docker image `justwatch/elasticsearch_exporter:1.0.2` so last released version `1.0.2`

**Comment by carlosjgp** [comment]
It might be useful to have a `Since` column on the documentation to avoid these misunderstandings

If you like the idea I can create a PR for it. Just let me know which parameters are not included yet

**Comment by zwopir** [comment]
I don't know when which parameter was introduced, so a since column would be filled quite sparsely... a quick note in the flag description would be sufficient. It's the only parameter only present in the master.
