### ISSUE TITLE
username/password not escaping properly

### ISSUE THREAD

**Issue by fatalglitch** [justwatchcom/elasticsearch_exporter#134]
When using random generated complex passwords with special characters, the exporter does not properly parse the URL string line.

```
docker run --rm -p 9108:9108 justwatch/elasticsearch_exporter '-es.uri=https://username:1234sa%x&Dk4PfwN@some.hostname.com:9200'

level=error ts=2018-03-24T20:30:21.697119444Z caller=main.go:48 msg="failed to parse es.uri" err="parse https://username:1234sa%x&Dk4PfwN@some.hostname.com:9200: invalid URL escape \"%x&\""
```

Is there a specific way to escape this in the docker-compose?

**Comment by beylisstan** [comment]
Hi, not sure that my case have same roots but now i guess that it is one of possible problem.
I am running elastic search by this way:

./elasticsearch_exporter -es.uri 'http://elastic:PAssword001!@localhost:9200' 

password include big, small letters numbers and char at the end "!".

Process is running as:
ps aux | grep elasticsearch_exporter

root      48419  0.0  0.0  12484  4800 pts/1    Sl   12:03   0:00 ./elasticsearch_exporter -es.uri http://elastic:PAssword001!@localhost:9200

When i am trying scrape metrics i am getting following error:

level=warn ts=2018-03-26T12:07:52.164479394Z caller=nodes.go:1359 msg="failed to fetch and decode node stats" err="HTTP Request failed with code 401"

**Comment by fatalglitch** [comment]
I was able to resolve this by changing the %x to %25x, which is the URL encoded version of %x

**Comment by fatalglitch** [comment]
@beylisstan try using https://www.urlencoder.org/ to encode your password string, see if that works

**Comment by dominikschulz** [comment]
@beylisstan @fatalglitch Please don't put your credentials on any third-party website. Use an offline encoder.
