### ISSUE TITLE
elasticsearch_indices_docs_primary metric is missing labels (cluster, es_***_node, etc..)

### ISSUE THREAD

**Issue by dannyk81** [justwatchcom/elasticsearch_exporter#135]
I'm using v1.0.2 of the exporter and looks like `elasticsearch_indices_docs_primary` is missing all the "default" labels that we find in other metrics: `cluster`, `es_***_node`, `host`

**Comment by dannyk81** [comment]
ping @zwopir 😄

**Comment by zwopir** [comment]
actually, it's not really a bug. The indices metrics are querying
`http://<host>:9200/_all/_stats?level=shards`.
This endpoint doesn't contain the values for the "default" labels, only the
node_id (some ES internal entity without external meaning). We've
implemented the metric classes as independent prometheus collectors. The
each call different ES API endpoints, each providing a different set of
information, so I don't really see a convenient way to correlate these
collectors without completely rewriting the exporter.

Can you elaborate on your use case so we can find a solution?!

**Comment by dannyk81** [comment]
We have multiple Elasticsearch clusters scraped by the same Prometheus server, and we use the `cluster` label in our queries to isolate the metrics per cluster.

Not having at least the `cluster` label makes it difficult to easily filter these metrics.

Currently I'm using a PromQL "hack" where I group these metrics with another (node) metric based on the instance label and extract the cluster label from there, it seems to work but was hoping to have these labels natively from the exporter.

**Comment by zwopir** [comment]
ok, I understand. It makes sense. To be honest, setting up a elasticsearch_exporter for each cluster seems like the easiest solution. The collectors that have/need label values from each other are completely independent. So correlating the label values would require some serious refactoring that doesn't make sense from any other point of view.

Maybe excluding the promQL-hack to recorded queries simplifies that usage of these metrics...?!

**Comment by dannyk81** [comment]
We are running elasticsearch_exporter on every elastic node, but they are all (nodes from all clusters) defined under the same job because we use Puppet based service discovery to build the targets list.

I already created a recording rule with the query I mentioned and we started using that in our dashboards, so not a big deal, though if this could be somehow fixed on the exporter level it would be stellar.

**Comment by zwopir** [comment]
ok, I understand your use case for the labels. I can't promise a short-term fix for your issue though, but I'll keep it in mind for a next refactoring round.

**Comment by zwopir** [comment]
Hi @dannyk81,

ideas are there for next refactoring round: we'll provided the sub-collectors with an update mechanism that provides the labels that are not know to the specific sub-collector from a update go routine. That routine regularly calls the ES on the `/` route to retrieve the cluster labels. Doing so, we ensure that
- we avoid calling the `/` route on every scrape in every sub-collector
- we avoid configuring static labels 
- the cluster labels are semi up to date without restarting the exporter

I can't promise to start within the next two weeks, but I wanted you to know there's at least some progress on this issue

**Comment by dannyk81** [comment]
Thanks for the update @zwopir! Looking forward for this 😃

**Comment by dannyk81** [comment]
Hey @zwopir, just wanted to check if this is still on track?

I see two PRs that seem to be addressing this (#162 & #143), but looks like they are somewhat stale.


Thanks!

**Comment by zwopir** [comment]
the track is still on. I wanted to give #162 the chance to incorporate the requested changes. If I don't receive feedback by tomorrow I'll do it myself.

**Comment by zwopir** [comment]
released: https://github.com/justwatchcom/elasticsearch_exporter/releases/tag/v1.1.0rc1
