### ISSUE TITLE
Prefix for index-level metrics

### ISSUE THREAD

**Issue by hudashot** [justwatchcom/elasticsearch_exporter#14]
I am going to implement index-level metrics using the [indices API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html). As I can see, the "indices" metric prefix is already used for metrics obtained via  [/_nodes/stats](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html) - for example, `indices_filter_cache_memory_size_bytes`.

I guess renaming the metrics is not an option, since multiple people are already using the exporter. I was thinking about using "index", i.e.:
- `index_filter_cache_memory_size_bytes` will have `cluster` and `index` labels
- `indices_filter_cache_memory_size_bytes` will remain as it currently is, with `cluster` and `node` labels

What do you think?

**Comment by hudashot** [comment]
@ewr, ping?

**Comment by nvx** [comment]
Index-level metrics might get a bit much depending on use (elasticsearch used with logstash usually has one index per day for example). I'd be in favour of being able to have this as an optional feature, or even better allow for aggregation by name (ie, aggregate logstash-httpd-* into a single logstash-httpd, or perhaps with a regex of something like s/-[0-9]{4}\.[0-9][0-9]\.[0-9][0-9]$// for example to dynamically strip off the dates off the end of index names to avoid having to list all patterns manually)
