### ISSUE TITLE
can't skip ssl verification "-es.ssl-skip-verify" 

### ISSUE THREAD

**Issue by slassh** [justwatchcom/elasticsearch_exporter#145]
******LOGS******
 flag provided but not defined: -es.ssl-skip-verify
es_exporter_1  | Usage of /bin/elasticsearch_exporter:
es_exporter_1  |   -es.all
es_exporter_1  |        Export stats for all nodes in the cluster.
es_exporter_1  |   -es.ca string
es_exporter_1  |        Path to PEM file that conains trusted CAs for the Elasticsearch connection.
es_exporter_1  |   -es.client-cert string
es_exporter_1  |        Path to PEM file that conains the corresponding cert for the private key to connect to Elasticsearch.
es_exporter_1  |   -es.client-private-key string
es_exporter_1  |        Path to PEM file that conains the private key for client auth when connecting to Elasticsearch.
es_exporter_1  |   -es.timeout duration
es_exporter_1  |        Timeout for trying to get stats from Elasticsearch. (default 5s)
es_exporter_1  |   -es.uri string
es_exporter_1  |        HTTP API address of an Elasticsearch node. (default "http://localhost:9200")
es_exporter_1  |   -web.listen-address string
es_exporter_1  |        Address to listen on for web interface and telemetry. (default ":9108")
es_exporter_1  |   -web.telemetry-path string
es_exporter_1  |        Path under which to expose metrics. (default "/metrics")

******docker-compose.yml******
    image: justwatch/elasticsearch_exporter
    command: ["-es.uri=https://user:passwd@server-ip:9200/" , "-es.ssl-skip-verify=true" ]
    restart: always
    ports:
    - 9108:9108

**Comment by zwopir** [comment]
thanks for reporting this - the docker container is a bit behind the latest master. I'll ping you here once we've updated the container in hub.docker.com

**Comment by zwopir** [comment]
@slassh there's a updated docker image on https://hub.docker.com/r/justwatch/elasticsearch_exporter/. The `latest` tag refers to v1.0.3rc1.
