### ISSUE TITLE
When you will release the next version?

### ISSUE THREAD

**Issue by ConorNevin** [justwatchcom/elasticsearch_exporter#149]
It's been a while and there a few things in master that haven't gotten a tag - any plans for a new release?

**Comment by zwopir** [comment]
Hi Conor,

there are no concrete plans, but it's on my list... I let you know - thanks for reminding me

**Comment by joaosilva15** [comment]
Any updates on this? I'm also interested in a couple of new features not yet released.

**Comment by zwopir** [comment]
just released v1.0.3rc1 - docker image is following in a minute

**Comment by zwopir** [comment]
thanks for you patience!
