### ISSUE TITLE
per-index metrics

### ISSUE THREAD

**Issue by caarlos0** [justwatchcom/elasticsearch_exporter#152]
Hi, thanks for the great work on this exporter!

So, it seems that the exporter query `/_all/_stats`, which returns all stats indeed 😄 

Those stats include:

- number of documents of all indices
- number of deleted documents of all indices
- index size in bytes

and others, but these 3 are the ones I miss :P 

Would you be interested in a PR adding support for reporting those metrics as well?

They may be interesting, for example, if the `rate(elasticsearch_index_deleted_document_count[5m]) by (index_name) > 1234` that means that  something is deleting a lot of documents or whatever...

Index size may also be useful to have the history of the index size and decide if we should reindex it with more or less shards and etc..

Anyway, let me know what you think. If you're interested, I'll work on a PR.

Cheers!

**Comment by dominikschulz** [comment]
That sounds like as useful improvement.
Would be nice if you'd create PR for that :+1:

**Comment by caarlos0** [comment]
@dominikschulz nice, check https://github.com/justwatchcom/elasticsearch_exporter/pull/153
