### ISSUE TITLE
the software cannot be adjusted to the operating system time

### ISSUE THREAD

**Issue by baoshengzhu** [justwatchcom/elasticsearch_exporter#154]
The software running output time is inconsistent with the operating system time. The time zone of my current system has been adjusted to China’s ZONE=“Asia/Shanghai”, but promethus cannot be adjusted to the operating system time.

cat /etc/sysconfig/clock 
ZONE="Asia/Shanghai"
UTC=false
ARC=false

**Comment by zwopir** [comment]
Hi baoshengzhu,

I don't exactly understand _where_ in the exporter/prometheus/... you are having the issue. The exporter itself (including the prometheus go client library) doesn't do anything with the current date/timestamp. The scrape timestamps are set on the prometheus server.

So you're either 1.) seeing a timestamp in the *metric value* that comes from the queried elasticsearch node or 2.) have a not correct timezone on the prometheus server. That would appear in the *metric timestamp* on the server.
Regarding 1.) : I had a brief look over the metrics. I may have missed it, but I'm pretty sure there is no metric in the exporter that exposes a timestamp. So I'm pretty sure it's 2.).

I hope this helps finding you issue.

**Comment by zwopir** [comment]
Hi @baoshengzhu,

I haven't heard back from you. Closing this issue as I think it's not an exporter problem. Don't hesitate to reopen it if thinks are unclear.
