### ISSUE TITLE
Disk usage metrics

### ISSUE THREAD

**Issue by djuarezg** [justwatchcom/elasticsearch_exporter#157]
I think it would be nice to have metrics related to the available space of space or the percentage of disk usage, as it would allow to trigger alarms whenever the node disks are filling up.

**Comment by dannyk81** [comment]
These metrics are already available, have you looked at:

elasticsearch_filesystem_data_available_bytes
elasticsearch_filesystem_data_size_bytes


Danny

**Comment by djuarezg** [comment]
You are right, misread them, sorry about the noise.

Thank you!

**Comment by djuarezg** [comment]
The problem with those metrics is that it only shows the metrics for one cluster node, not in total, and there are not multiple entries for each of the nodes.
