### ISSUE TITLE
snapshots/repositories metrics

### ISSUE THREAD

**Issue by sp-francisco-manas** [justwatchcom/elasticsearch_exporter#161]
Hi,

We're using this exporter with excellent results, thanks for the great work!

The only thing we're missing are snapshots/repositories metrics so we can add alerts in case some snapshot has failed or it's not being done.

The exporter will need to query another URLs to get the info:
- repository list: http://localhost:9200/_cat/repositories
- repository info (snapshots list): http://localhost:9200/_cat/snapshots/repository

If you think it makes sense to have this metrics, please let me know so we can work on a PR.

Cheers

**Comment by zwopir** [comment]
Hi Francisco,

having metrics about snapshots certainly makes sense. We currently retrieve those with a separate gcp-specific, non-opensource exporter, but having a more generalized snapshot metrics in the exporter would be nice. If you feel confident creating you can create a PR and I will happily review it - after the weekend, as I'm currently on holidays with my kids. If you need help, I can help you alter the weekend as well

**Comment by zwopir** [comment]
Hi @sp-francisco-manas,

I'm back from holidays. Are you working on a PR? do you need help?

**Comment by sp-francisco-manas** [comment]
Hi @zwopir 

Sorry for the late reply, i've been on holidays too. I'm working on a PR, i hope to have it soon

Thanks
