### ISSUE TITLE
Prometheus port should be 9114

### ISSUE THREAD

**Issue by mjtrangoni** [justwatchcom/elasticsearch_exporter#165]
Hi @dominikschulz @zwopir ,

This exporter has port 9114 [here](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) reserved, but in [README.md](README.md) and also the exporter default port itself is 9108.

**Comment by zwopir** [comment]
Hi @mjtrangoni,

thanks for the heads up! I'll change it with the next release. Unfortunately this is a breaking change

**Comment by hackery** [comment]
btw https://hub.docker.com/r/justwatch/elasticsearch_exporter still uses 9108.

**Comment by zwopir** [comment]
the latest RC changed the port to 9114
