### ISSUE TITLE
Index_failed metric

### ISSUE THREAD

**Issue by ionutancuta** [justwatchcom/elasticsearch_exporter#166]
Hi,

Activating the -es.indices(shards) flag I see that no metric related to index_failed is extracted. Should any development needs to be done in the code to have this?

**Comment by zwopir** [comment]
Hi @ionutancuta,

the json field is not exposed as a metric, so this needs to be implemented if you like to have such a metric. The value is unmarshaled from the json, you can find it in https://github.com/justwatchcom/elasticsearch_exporter/blob/master/collector/indices_response.go#L65. Exporting it should be straight forward. Ping me if you need help

**Comment by zwopir** [comment]
fix by #281
