### ISSUE TITLE
Switch from flag to kingpin

### ISSUE THREAD

**Issue by mjtrangoni** [justwatchcom/elasticsearch_exporter#173]
Hi @zwopir,

This is issue is a reminder for switching to [kingpin](https://github.com/alecthomas/kingpin) as many other exporter does.

As a breaking change, this should be done shortly before a breaking change release.

**Comment by metalmatze** [comment]
Is there anything with the current flags, that doesn't work for you? Why would you want to move to the new library? Please elaborate. Thanks.

**Comment by dominikschulz** [comment]
I don't see any good reason to move to kingpin.
But also no good reason not to, in case someone is eager to work on that.

**Comment by zwopir** [comment]
My pros for kingpin
- automatically supports configuration via environment variables
- supports long and short options. This not very important as you usually don't have to call the binary very often
- POSIX compatible flags

Cons are:
- its a breaking change
