### ISSUE TITLE
Cannot find the corresponding metrics which write in dashboard.json

### ISSUE THREAD

**Issue by shuangyangqian** [justwatchcom/elasticsearch_exporter#181]
1.in https://github.com/justwatchcom/elasticsearch_exporter/blob/v1.0.4rc1/examples/grafana/dashboard.json#L156
we can see that the metric is `node_memory_MemTotal`, but i cannot find the corresponding metrics in 
https://github.com/justwatchcom/elasticsearch_exporter/tree/v1.0.4rc1#metrics , i don't know why.
2.when execute elasticsearch_exporter, and `curl localhost:9108` ,  if i can see the metrics which write in https://github.com/justwatchcom/elasticsearch_exporter/tree/v1.0.4rc1#metrics? 
3. if anyone can explain me that the difference between the metrics in the three places:

- https://github.com/justwatchcom/elasticsearch_exporter/blob/v1.0.4rc1/examples/grafana/dashboard.json
- https://github.com/justwatchcom/elasticsearch_exporter/tree/v1.0.4rc1#metrics
- curl localhost:9108
 
thank you very much.

**Comment by zwopir** [comment]
Hi, 
you won't find the metric in the exporter, as it comes from the node_exporter. This is documented in https://github.com/justwatchcom/elasticsearch_exporter#alerts--recording-rules. If you don't have the node_exporter installed, you can use the internal metrics. These are:
```
# HELP elasticsearch_jvm_memory_committed_bytes JVM memory currently committed by area
# HELP elasticsearch_jvm_memory_max_bytes JVM memory max
# HELP elasticsearch_jvm_memory_pool_max_bytes JVM memory max by pool
# HELP elasticsearch_jvm_memory_pool_peak_max_bytes JVM memory peak max by pool
# HELP elasticsearch_jvm_memory_pool_peak_used_bytes JVM memory peak used by pool
# HELP elasticsearch_jvm_memory_pool_used_bytes JVM memory currently used by pool
# HELP elasticsearch_jvm_memory_used_bytes JVM memory currently used by area
# HELP elasticsearch_process_mem_resident_size_bytes Resident memory in use by process in bytes
# HELP elasticsearch_process_mem_share_size_bytes Shared memory in use by process in bytes
# HELP elasticsearch_process_mem_virtual_size_bytes Total virtual memory used in bytes
```
