### ISSUE TITLE
Helm chart has two liveness probes and no readiness probe

### ISSUE THREAD

**Issue by iainduncani** [justwatchcom/elasticsearch_exporter#187]
Unlike the example deployment.yaml file:

https://github.com/justwatchcom/elasticsearch_exporter/blob/master/examples/kubernetes/deployment.yml#L53

which has a readiness probe and a liveness probe the helm chart has a second liveness probe:

https://github.com/helm/charts/blob/master/stable/elasticsearch-exporter/templates/deployment.yaml#L83

**Comment by zwopir** [comment]
Hi @iainduncani,

thanks for reporting this. It's certainly not correct, but we're not owner of the helm charts repository.

**Comment by iainduncani** [comment]
Ah OK, I wasn't really sure how the two linked up and assumed you push a new helm chart when something over here is updated.  I didn't want to just send them a PR as I wasn't sure what the policy around version etc. was!
