### ISSUE TITLE
Inconsistent metrics

### ISSUE THREAD

**Issue by alanwds** [justwatchcom/elasticsearch_exporter#190]
I'm querying by elasticsearch_indices_store_size_bytes_total metric in a time range:

```
elasticsearch_indices_store_size_bytes_total{index=~"myIndexPattern",instance="localhost:9108",job="elasticsearch_exporter"}[1d]
```
My indices getting bigger with the time, but, i can see newest entrys with small values if you compair with olderst entrys. For example:

```
567380 @1539703651.069 <- 1 entry
597310 @1539703951.069 <- 2 entry (bigger than last)
628706 @1539704251.069 <- 3 entry (bigger than last)
737724 @1539704551.069 <- 4 entry (bigger than last)
404994 @1539704851.069 <- 5 entry (SMALLER than last)
```

I'm trying understand the reason for that. Any ideias?

PS: es.timeout is setted to 60s. My cluster return /_all/_stats in ~ 20s. My scrape is configured to 300s.
PS2: I don't delete any data from my indices

Best Regards,

**Comment by alanwds** [comment]
One more information. ES cluster version 2.2.0.

I also wrote a little script that calls /_all/_stats API each 300s. The API return values with the same problem:

```
"size_in_bytes": 293095500968,
"size_in_bytes": 300620375168,
"size_in_bytes": 306603609543,
"size_in_bytes": 304666606593, <- small then last
"size_in_bytes": 311070026233,
"size_in_bytes": 321492104677,
"size_in_bytes": 336814439858,
"size_in_bytes": 331227706664, <- small then last
```

That's mean the exporter have no problem. To clarify the things, we did another test using /_cat/indices API:

```
data=$(date)
result=$(curl -s '10.0.1.249:9200/_cat/indices?bytes=b' | grep MyIndice | awk '{sum+=$8} END {printf "%.f\n",sum}')
echo $data:$result >> /tmp/MyIndiceSize
```

The results are wrong too.

Maybe, at merge of the segments cause a decrease of index size.

Anyway, i'll close this issue.

Thank's

**Comment by zwopir** [comment]
I was about to write the same: the exporter is just pulling the metrics from the stats endpoint and exposes them more or less unmodified as metrics
