### ISSUE TITLE
connection refused to get the cluster health

### ISSUE THREAD

**Issue by kiranps11** [justwatchcom/elasticsearch_exporter#192]
Hello,

The exporter is failed to collect the cluster health metric
and i am using the docker image to running  below command.

docker run --rm -p 9108:9108 justwatch/elasticsearch_exporter:1.0.2

Error:
level=warn ts=2018-11-06T08:55:36.294511261Z caller=nodes.go:1359 msg="failed to fetch and decode node stats" err="failed to get cluster health from http://localhost:9200/_nodes/stats: Get http://localhost:9200/_nodes/stats: dial tcp 127.0.0.1:9200: getsockopt: connection refused"

**Comment by zwopir** [comment]
Hi @kiranps11,

you need to specify the URL of your ES node via `-es.uri`. Please note that `localhost:9200` will not work even if you run the container on the ES node - it refers to the docker container, not the host machine unless you specify `--net=host`, which I don't recommend. So the docker command must be something like
```
docker run --rm -p 9108:9108 justwatch/elasticsearch_exporter:1.0.2 -es.uri http://<ip_of_you_es_node>:9200
```

**Comment by zwopir** [comment]
I assume that solved the problem, as I don't see it as a problem of the exporter itself, I'll close the issue.
