### ISSUE TITLE
how should I to pass phrase for the private key?

### ISSUE THREAD

**Issue by shiyapeng** [justwatchcom/elasticsearch_exporter#198]
my private key has the phrase ,how should I  pass phrase for the private key?

**Comment by zwopir** [comment]
Hi @shiyapeng,

password protected private keys are currently not supported. Until I or someone else implements it, the only thing you can do is to convert the key to an unencryped one. You can use `openssl rsa -in encrypted_file.pem -out unencrypted_file.pem` to do so

**Comment by zwopir** [comment]
after thinking about this, it actually doesn't make sense to me. If we implement unlocking the key with a passphrase in the exporter, we have need the passphrase provided as environment variable or commandline parameter. This is as secure as having the unencrypted private key lying around where the exporter can access it. Closing the issue
