### ISSUE TITLE
Expose previously added metrics from the `_nodes/_local/stats` API

### ISSUE THREAD

**Issue by onimisionipe** [justwatchcom/elasticsearch_exporter#199]
Following this closed issue: https://github.com/justwatchcom/elasticsearch_exporter/issues/115, we discovered those metrics were added from the indices stats and requires the `-es.indices` option set to true. This is great but we would like to also include group stat metrics via the cluster stats API here: https://www.elastic.co/guide/en/elasticsearch/reference/6.2/cluster-stats.html

We would also love to add the metrics listed in https://github.com/justwatchcom/elasticsearch_exporter/issues/115 to https://github.com/justwatchcom/elasticsearch_exporter/blob/master/collector/nodes.go.

This will be great for our environment.
This is being tracked here: https://phabricator.wikimedia.org/T210592

Thanks!

**Comment by zwopir** [comment]
Hi @onimisionipe,

thanks for opening the issue and pointing us at the `/_cluster/stats` endpoint. I wasn't aware of it.
It makes sense to include the provided metrics as an optional collector, although I'm wondering if the metrics can't be obtained via promQL aggregation over the indices metrics.

If not, a PR is very welcome. I'll happily help if you have any questions.

I'm not sure if I'm understanding your question regarding the #115-metrics addition to the nodes collector correctly. Currently every collector does exactly one call to one of the ES API endpoints. Are the metrics mentioned in #115 included in the `_nodes/stats` endpoint?

**Comment by onimisionipe** [comment]
The metrics in https://github.com/justwatchcom/elasticsearch_exporter/issues/115 can be added from `/_cluster/stats`

**Comment by zwopir** [comment]
ah, ok. Thanks for looking it up. Can you contribute a PR? Unfortunately I don't have the time to do it myself.

**Comment by onimisionipe** [comment]
Alright. I will see what I can do. My golang is not really good :)

**Comment by zwopir** [comment]
thanks! Let me know if you need help

**Comment by onimisionipe** [comment]
Hello!
Could you look into this please
