### ISSUE TITLE
Expose name and date of index in separate fields

### ISSUE THREAD

**Issue by joaopereiramrf** [justwatchcom/elasticsearch_exporter#201]
As we want to do some aggregations by name and date of index, we need to expose name and date together with the format "index_name-date".

example:
elasticsearch_index_stats_fielddata_evictions_total{index=".kibana-20180630",**indexDate="20180630"**,**indexPrefix=".kibana"**} 0

PR: #200

**Comment by zwopir** [comment]
Hi @joaopereiramrf,

thanks for raising this issue and the PR. Unfortunately the PR only fits for your use case: the PR only works if the indices names follow the format `index_name-<date>`. This is not always the case and would return garbage label values for all users that don't use that format.

So this needs to be solved on a per-setup level. I suggest using prometheus relabel configs for that. It supports creating/rewriting metric labels based on regex matchers.
