### ISSUE TITLE
es.cluster_settings not recognized 

### ISSUE THREAD

**Issue by Gappa88** [justwatchcom/elasticsearch_exporter#202]
hi,

I'm trying to use `elasticsearch_exporter` in order to export ES' statistics to **Percona** using `pmm-admin` tool to fire the scraping. 

I have downloaded the 1.0.2 and the latest Docker versions of `elasticsearch_exporter` but it continues to give me "cannot parse cluster health", so I have downloaded the pre-built binary **1.0.4rc1.linux-386**.

I have launched `1.0.4rc1.linux-386` this way:
`./elasticsearch_exporter -es.all=true -es.indices=true -es.shards=true`
and it works, I can see stats in the Percona's Grafana Dashboard **but** I have no information about **cluster**.

I also checked the exporter's options and I found `es.cluster_settings` but it isn't recognized by the `elasticsearch_exporter`

**Comment by TheMeier** [comment]
`es.cluster_settings` is new and not released yet

**Comment by TheMeier** [comment]
Which documetation are you refering to? The readme of the current release certainly does not have thate parameter: https://github.com/justwatchcom/elasticsearch_exporter/blob/v1.0.2/README.md

**Comment by Gappa88** [comment]
in the homepage:
[https://github.com/justwatchcom/elasticsearch_exporter](https://github.com/justwatchcom/elasticsearch_exporter)

**Comment by TheMeier** [comment]
Well that shows the README.md of the git master branch. You need to look at the one fro the version you are using. Also running `elasticsearch_exporter --help` locally will show you what is actually correct with the version you have.

**Comment by Gappa88** [comment]
my bad, thanks

**Comment by zwopir** [comment]
Thanks @TheMeier for helping out with the issue. I'm currently on vacation, but will try to release a new RC once I'm back
