### ISSUE TITLE
how to add discovery for prometheus

### ISSUE THREAD

**Issue by adoo123** [justwatchcom/elasticsearch_exporter#204]
Could you write a discovery config for prometheus in /example/prometheus,like:
    - job_name: 'kubernetes-cadvisor'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

**Comment by TheMeier** [comment]
@adoo123 how is this related to elasticsearch_exporter?

**Comment by adoo123** [comment]
@TheMeier Because when I run the deployment of elasticsearch-export,I couldn't search any key of ES on prometheus.

**Comment by TheMeier** [comment]
Still this is a general prometheus kubernetes_sd topic and not specific to elasticsearch_exporter

**Comment by adoo123** [comment]
@TheMeier how to fix it or do you hava a doc for install  elasticsearch_exporter with k8s expect use helm
