### ISSUE TITLE
Avg. CPU Usage graph returns no data

### ISSUE THREAD

**Issue by MaxDiOrio** [justwatchcom/elasticsearch_exporter#205]
Not sure why.

irate and/or rate for node_cpu doesn't actually return any node_cpu items, only beta_kubernetes_io_arch.   If I do a simple avg(node_cpu...   I get the proper elements.

<img width="990" alt="image" src="https://user-images.githubusercontent.com/25855524/49877929-7b765400-fdf4-11e8-9796-420674fe44be.png">

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/25855524/49877991-9d6fd680-fdf4-11e8-90de-9d562b2884c7.png">

**Comment by zwopir** [comment]
Hi Max, 

this is not an elasticsearch_exporter issue, but a node_exporter issue. Trying to help anyways: the node_cpu metric is a counter, so the query you are looking for is
```sum(rate(node_cpu[10s])) by (mode)```

Have a look at Brian Brazil's Blog (robustperception.com). If I remember correctly there's an article about exactly that metric
