### ISSUE TITLE
impossible to reach elasticsearch via VPN or basic auth+ssl

### ISSUE THREAD

**Issue by Gappa88** [justwatchcom/elasticsearch_exporter#210]
hi,

I'm trying to use **docker elasticsearch_exporter 1.0.2** but I'm stuck because I get 
`msg="failed to fetch and decode cluster health" err="failed to get cluster health from http://10.10.0.1:9200/_cluster/health`

At the first shot I thought it was caused by elasticsearch that is listening on an VPN interface and the docker cannot reach it, so I tried to make the docker requests to the Nginx process running on the same machine where ES is running but I get 
`msg="failed to fetch and decode cluster health" err="failed to get cluster health from https://user:password@mysite:443/_cluster/health`

recap:
2 ways to reach ES:
- via VPN, without basic auth, directly to es listening port
- via internet contacting nginx reverse proxy with SSL and basic auth

how can I solve this?

**Comment by zwopir** [comment]
Hi @Gappa88,

this doesn't sound like an exporter issue itself. Rather like a general docker/networking issue. Can you exec into the container (it's based on busybox) and check if you can ping/netcat/... the ES IP?

**Comment by Gappa88** [comment]
hi @zwopir ,

I logged in to the docker via:
`docker exec -it container_id sh`

and I successfully ping any local or remote or vpn ips.
I tryed to `curl` the ES url in order to verify the connection to the server but there is no curl program installed. 
Is there any other test to do? I really don't understand why it doesn't work, I'm pretty sure it is my fault but I'm stuck.

Thanks

**Comment by zwopir** [comment]
`wget` is installed in the container. So you can do a 
```
wget http://<IP>:9200 -O -
```

**Comment by Gappa88** [comment]
thank you @zwopir I finally found the solution. It was caused by a bad firewall rule.
