### ISSUE TITLE
Problems with set parameters

### ISSUE THREAD

**Issue by morenweld** [justwatchcom/elasticsearch_exporter#216]
Hi. I use elasticsearch_exporter v1.0.4rc1 pre-built binarie for linux-amd64.
It work for default values but i can't change **-ec.uri**. I get error "**flag provided but not defined: -ec.ur**i"
I tried to execute : `elasticsearch_exporter --ec.uri="http://localhost:9201"` with double and single quotas and dashes.
What i do wrong?
Note: `elasticsearch_exporter --web.listen-address=":9109"` works good.
Also i tried do download versions 1.0.3 and 1.0.2 but i got the same error.

**Comment by zwopir** [comment]
the parameter is `-es.uri`, not `-ec.uri`

**Comment by morenweld** [comment]
Thanks you very much. It really so stupid mistake.
