### ISSUE TITLE
How to set log level in the latest RC?

### ISSUE THREAD

**Issue by vipinchadha** [justwatchcom/elasticsearch_exporter#218]
Hi,

Can you point me to the parameter required to set the log level in the 1.0.4rc1. Which release artifact can be used for Redhat7 64bit?

Thanks

Vipin

**Comment by zwopir** [comment]
you can set the log level with `-log.level debug`. The latest RC uses POSIX style arguments, that is `--log.level debug`. You can always refer to the buildin help (`-h`)
