### ISSUE TITLE
Add index_stats_search_scroll_current metric

### ISSUE THREAD

**Issue by adeesent** [justwatchcom/elasticsearch_exporter#220]
Greetings!

As I can see, there is a such field in struct, but no metric exposed - https://github.com/justwatchcom/elasticsearch_exporter/blob/c36d0a21ea7e3195297e1de1a77fd1ce93103d30/collector/indices_response.go#L104

**Comment by zwopir** [comment]
Hi @adeesent,

we happily accept PRs, especially if they don't introduce extra calls to ES API endpoints. I probably releasing a new release candidate within the next week, so if you're fast, the PR can make it into the next release. Let me know, if you need help
