### ISSUE TITLE
How to know when a Data Node jumps out of cluster with http disabled on endpoint?

### ISSUE THREAD

**Issue by Komodoro** [justwatchcom/elasticsearch_exporter#224]
Hello,
This is more of a **question** then anything else. I've been reading the issues created in the project but no one has a similar situation to mine. So I decided to start this issue.
I'll be brief and try to explain properly. This might help someone in the same situation.

I have the elastic data nodes without **http enable** because in our (company) case they should never since the objective is not to be able to make queries to them directly, So we have that **disable** since it would as well destroy the whole purpose of being a data node. For queries we have the clients.

After this, we have a load balancer with a subdomain name configured to point to our cluster... so our es.uri flag is set to point to the cluster url instead of pointing to the instance/localhost.

So far so good. We use the exporter, in most of the cases, for dashboards and for alerts with alertmanager configured. If we lose a client the exporter/prometheus will warns us about it by checking cluster_health_up metric which identifies that the node is in the cluster or not. This has been flawless on clients even if we are pointing to the load balancer url, making it unpredictable cause one day he will not be scraping correctly and we'll lose a client without knowing. But for now it is working cause we are checking other metrics that help us figure this out real quick.

But our biggest problem, so far, are the data nodes. We can't monitor data nodes efficiently without having some kind of recording rule to check the number of data nodes and check if the value changes.  Since we have http disabled we cannot receive this information even pointing to the cluster url like our clients are. The elastic api on /_node/stats shows all hosts names that are available on the cluster and that a data node left. But the exporter doesn't seem to have any info about this nor does make use of the fes.node flag not correlating and comparing that information.
It could come in handy for the exporter to set it self up, in the metrics that it exposes, as down or something on the data node that is out of the cluster when he compares es.node to the list of machines in /_nodes/stats.

P.S.: I'm not a great developer but I would be interested in submitting/forking this solution if possible. Cause for our use case, I know metrics are not values to take into consideration for creating alarms straight on through like if it was nagios, but since they are there and they are fast/reliable enough to make a good triage, why not using them?

Hope anyone could help.

**Comment by zwopir** [comment]
Hi @Komodoro ,

you said "The elastic api on /_node/stats shows all hosts names that are available on the cluster and that a data node left.". Can you provided me with the output of the `/_nodes/stats` in such a condition. It should be relatively easy to add the missing metrics if the underlying values show up in the stats endpoint response.

As a completely different solution: you could expose the data nodes http API only on localhost and run the recommended setup "one exporter per ES node". The exporters would then run on the nodes directly

**Comment by Komodoro** [comment]
Hey @zwopir 
Thanks for the reply.

I know that maybe this isn't the best way to do it but I'm studying if I can parse the elastic api as a json list and compare it with the flag "es.node" (c.node) value to the existing list. 
If the node exists it would return 1, but if it didn't it would return 0. Cause we know for a fact that the node should be in the cluster 
I know that this is a bit flawed and maybe is only specific to the company case I work for. Destroying all the purposes of using metrics of the service to warns (using alertmanager) of any inconvinience.
We know how to be alarmed when a data node jumps out of the cluster, but which one? We use most of our alarms with regex so it affects more then one of two specific machines. Having loads of hosts with elasticsearch and having this kind of feature enabled would help a lot.
So I would propose another flag for this kind of situation, so not to go into conflict with the other scenarios that don't apply, to be possible for data nodes elastic exporters to querie the cluster url endpoint and extract the values of its node and know his own status through the help of a client that answers to that loadbalanced url.

And I got the api path wrong:
`/_cluster/state/nodes`
I don't know how to go further than this. 
I'll post a pastebin example of what I see on that link:

https://pastebin.com/VFFrfhaw

If any of the nodes jumps out of the cluster, they dissapear from that list on that path.
Comparing the c.node value against that list could turn out to be useful and straight to the point.

Yes, we could but I was talking with the rest of the team and they don't want to be force to that on a data node when the data node is just to ingest and not to be queried in either way.
Since having the node name in the cluster api path is possible to check the data node metrics I figured it could be done something similar as state above (like a comparison of some sort)

The same person that proposed the es.node flag works around the place I'm at aswell.

We know this may be a wet dream on perfect scenarios. But I thought I could give it a shot and create an issue exposing the case before I start doing anything to propose here so I didn't get all my work shattered.

 Sorry for the long text. If I wasn't clear please do tell.

**Comment by zwopir** [comment]
I hope I'm understanding you correctly: you more or less want to compare cluster state represented by the `nodes` maps the `/_cluster/state/nodes` endpoint at two different points in time. With the elasticsearch_exporter there's no way of doing this because the exporter doesn't keep any state of it's previous run (run = scrape from any prometheus). Another reason this is not possible in the elasticsearch_exporter is that a change in the list is only visible on two consecutive endpoint calls. The third api call won't show the diff (call 1) -> (cluster changes) -> (call 2 detects the change) -> (no cluster change) -> (call 3 doesn't see a difference to call 2).

I would approach the problem like following:
 - create a periodic job that queries the above endpoint
 - on each iteration, diff the maps (I suggest using the node id as a diff key)
 - on a diff, push the detected change to a prometheus pushgateway

As a metric I would send the unix timestamp of the detected change time with the node name as label. This way you can alert on `(time() - last_change_ts) < 60*60*30` (there's been a cluster change in the last 30min).

**Comment by zwopir** [comment]
this is a pretty specific use case which I won't implement in the elasticsearch_exporter. The push gateway and the pushgateway client package is pretty well documented.

**Comment by Komodoro** [comment]
> I hope I'm understanding you correctly: you more or less want to compare cluster state represented by the `nodes` maps the `/_cluster/state/nodes` endpoint at two different points in time. With the elasticsearch_exporter there's no way of doing this because the exporter doesn't keep any state of it's previous run (run = scrape from any prometheus). Another reason this is not possible in the elasticsearch_exporter is that a change in the list is only visible on two consecutive endpoint calls. The third api call won't show the diff (call 1) -> (cluster changes) -> (call 2 detects the change) -> (no cluster change) -> (call 3 doesn't see a difference to call 2).

Half a truth. I want to compare, yes but not at two different points in time. Sorry maybe I'm not being clear.
I'm passing this values to elasticsearch_exporter on my data.node with **http enabled=false**.
`-web.listen-address=:5108 -es.uri=http://cluster-name.domain.local:9200 -es.ssl-skip-verify -es.timeout='9s' -es.node='DATANODE01'` This is passing through a loadbalancer. Where our clients also have logstash and kibana. So the LoadBalancer points to the clients.
I would like to use the value at: `-es.node=` flag to compare with the parsed list from  `/_cluster/state/nodes` on the cluster link. Cause the names I have in my nodes, in the flags, are the same that the cluster sees. So the comparison stamente would have the objective of finding the same object name on my es.node flag within the json list. So only that es exporter at that node would fire off the alarm.

What happens now is: Whenever the datanode01 goes down/jumps out of cluster the client node parses the info he has of the datanode01 still. Because the nodes, when in a cluster, also have info on the other nodes (good stuff going on here, good job with this). 
Even if some metrics disappear, which is a different way to know it went down like with delta function or offset, this is only valid for a timeframe period comparison. When that time frame catches up with a faulty value and the node goes down I would never know for sure if any node went down. But if I'm comparing in real time scrape I know for sure what happened. Having a metric gauge setting of 1 or 0 for whenver he finds the name or not would help identify faster which node went down. 

I think I was clearer. 

But ok, I thought that it could be possible to implement a different kind of collector pointing to that path of the endpoint I mentioned.

> 
> I would approach the problem like following:
> 
>     * create a periodic job that queries the above endpoint
> 
>     * on each iteration, diff the maps (I suggest using the node id as a diff key)
> 
>     * on a diff, push the detected change to a prometheus pushgateway
> 
> 
> As a metric I would send the unix timestamp of the detected change time with the node name as label. This way you can alert on `(time() - last_change_ts) < 60*60*30` (there's been a cluster change in the last 30min).

We don't have pushgateway in our infrastructure management but this may be a good time to do it.

But I'll wait for a new response of the clearer idea of what I stated. But I get your point. This is going against the idea behind capturing only the metrics that the api hands out.

**Comment by zwopir** [comment]
yes, you're right with the last sentence. I also think your use case is a bit too specific to include it in the exporter. Sorry I can't help you here.

**Comment by zwopir** [comment]
by the way, we (justwatch.com) launched today in Portugal :)

**Comment by Komodoro** [comment]
@zwopir Nice, congrats.
I'll check it out. 😃 

Let me just be sure on one thing you mentioned above. 
>this is a pretty specific use case which I won't implement in the elasticsearch_exporter.

>I also think your use case is a bit too specific to include it in the exporter.

My English is a bit rusty and sometimes I don't understand things at first glance. 
Just to be clear and sure about what you stated:
- you wouldn't accept a possible fork from us with this idea on it or would you? Even if we spent our own time developing it on your source?

Don't judge me wrong. And sorry If I'm being a pain.
It is in our fullest and deepest interest in keep supporting this and moving forward.
Maybe there are other people who may be, one day, in the same situation as we are.
But until that happens we respect any answer given and try for the push-gateway solution.

**Comment by ekarak** [comment]
well why not use `elasticsearch_cluster_health_number_of_data_nodes` for this? you can create a prometheus alert when 
```
- expr: elasticsearch_cluster_health_number_of_data_nodes < max_over_time(elasticsearch_cluster_health_number_of_data_nodes[60m])
  for: 5m
```
this alert will fire for 55 minutes when the nr of data nodes drops by at least 1.

**Comment by Komodoro** [comment]
> 
> 
> I'd keep it as simple as possible. Why not use `elasticsearch_cluster_health_number_of_data_nodes` for this? you can create a prometheus alert when the nr of data nodes drops by at least 1:
> 
> ```
> - expr: elasticsearch_cluster_health_number_of_data_nodes < max_over_time(elasticsearch_cluster_health_number_of_data_nodes[60m])
>   for: 5m
> ```
> 
> this alert will wait for 5 minutes (eg. rebooted nodes) and then fire for 55 minutes

I have that applied. I've thumbed you up because what you've said is a good solution for a cluster with like 10 nodes.
But that is impracticable when I have 120 nodes in a cluster, and 50 are data nodes with the config I mentioned above. Just giving round numbers here. But we have clusters that are this big. We have more than one cluster like this. And some cluster have different naming conventions but always with a counter in the name to know which one is it easier. If the first or the last numbers are missing we would know, but what about those in the middle? They are easier to miss?
I could make a recording rule on this and put a vector (0) to spill this out, but this wouldn't tell me if the node is out of the cluster. The thing here is to read out of the API. And since we have a flag --es.node with the same value name as the ones that the machines have he could read off of himself on /_cluster/state/nodes and check if he exists. If he doesn't he would himself warn us.

**Comment by ekarak** [comment]
ok then how about a quick-n-dirty solution: use a script to dump ES cluster state (essentially the timestamp of 'last seen alive' per each node), then use the textfile collector facility in node_exporter to have the metrics scraped. Then you can alert if a node's last timestamp is older than a threshold

**Comment by Komodoro** [comment]
> 
> 
> ok then how about a quick-n-dirty solution: use a script to dump ES cluster state (essentially the timestamp of 'last seen alive' per each node), then use the textfile collector facility in node_exporter to have the metrics scraped. Then you can alert if a node's last timestamp is older than a threshold

Do I need to have this running in a cronjob?
If I understand what is in node_exporter page is that the exporter with the flag scrapes the files from the directory. 
Than I don't need to compare ... I guess...

**Comment by zwopir** [comment]
> Do I need to have this running in a cronjob?
yes, the node_exporter textfile feature only picks up the content of a file, it doesn't trigger any script executions
