### ISSUE TITLE
 How to monitor multiple ES clusters by using elasticsearch_exporter?

### ISSUE THREAD

**Issue by hepyu** [justwatchcom/elasticsearch_exporter#225]
RT.

 How to monitor multiple ES clusters by using elasticsearch_exporter?

**Comment by zwopir** [comment]
Hi @hepyu,

we recommend to have an exporter running on every node of the cluster (with the flag `-es.all` not set). If you can't run it on the nodes, you have to run a separate exporter per cluster

**Comment by hepyu** [comment]
@zwopir 
Yes, it I used multi es_exporter process, its ok. 

But I want to use docker method to deploy multi es_exporter, there was some problem: docker only could start one container to monitor one es cluster. If I start second es_exporter with docker, the fisrt es_exporter container will be replaced, then how to solve this problem?

3Q~

**Comment by hepyu** [comment]
this is my docker configs:

![image](https://user-images.githubusercontent.com/3917749/53382970-f7724800-39b0-11e9-845e-d59681e6a204.png)

![image](https://user-images.githubusercontent.com/3917749/53382981-035e0a00-39b1-11e9-825d-ae899248d9bc.png)

**Comment by hepyu** [comment]
I have solved this, my mistake, ports configs invalid. 3Q.

**Comment by hepyu** [comment]
it should be like this:
![image](https://user-images.githubusercontent.com/3917749/53385115-4b345f80-39b8-11e9-8a87-9ae814b97b53.png)

**Comment by craigfurman** [comment]
Hi @zwopir, sorry to post on an old thread. We run our elastic clusters in a managed provider, that does not (yet) install this exporter on each node. We run an external instance of this exporter using `-es.all`, and as you say here, we must run one per cluster.

Would you be interested in a PR that allows multiple clusters to be externally scraped by one exporter? This might need a breaking change to the config schema, but I've not looked into it deeply yet.
