### ISSUE TITLE
Cert and key are not added when use es.ssl-skip-verify flag

### ISSUE THREAD

**Issue by wojciechss** [justwatchcom/elasticsearch_exporter#227]
./elasticsearch_exporter -es.uri=https://192.168.99.100:30932 -es.client-cert=cert.pem -es.client-private-key=key.pem -es.ssl-skip-verify=true
level=info ts=2019-02-26T07:27:08.475584447Z caller=main.go:95 msg="starting elasticsearch_exporter" addr=:9108
level=warn ts=2019-02-26T07:27:21.640891195Z caller=cluster_health.go:284 msg="failed to fetch and decode cluster health" err="HTTP Request failed with code 401"
level=warn ts=2019-02-26T07:27:21.646769864Z caller=nodes.go:1519 msg="failed to fetch and decode node stats" err="HTTP Request failed with code 401"

Fix for this is: https://github.com/justwatchcom/elasticsearch_exporter/commit/e50a3f4f5474d2c53d1cdaae5543bcc1b4f2c892, but it is not released yet

Where I can expect newest release with this change?

**Comment by zwopir** [comment]
just released a RC. Have a look at https://github.com/justwatchcom/elasticsearch_exporter/releases
