### ISSUE TITLE
Problem with set custom parameter on docker container.

### ISSUE THREAD

**Issue by HowYeahYu** [justwatchcom/elasticsearch_exporter#230]
Hi. The image was pulled on DockerHub and I was run the following command to start a new container.
`
docker run -it --entrypoint "/bin/elasticsearch_exporter --es.uri='http://192.168.33.10:9200' --web.listen-address=':9114' " justwatch/elasticsearch_exporter
`
and then I got the result:
`
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/bin/elasticsearch_exporter --es.uri='http://192.168.33.10:9 200' --web.listen-address=':9114' \": stat /bin/elasticsearch_exporter --es.uri='http://192.168.33.10:9200' --web.listen-address=':9114' : no such file or directory": unknown.
`

So, Is it the wrong way to set custom parameters? Does it have another way to specify custom configs?

**Comment by zwopir** [comment]
you can simply run
```
docker run --rm -p 9114:9114 justwatch/elasticsearch_exporter:1.1.0rc1 --es.uri= ...
```

please note that `latest` points to the latest stable version, which is 1.0.2. Here the port is 9118 and the commandline arguments are prefixed with single dashes. I encourage you to try the release candidate though (as done in the example above)

**Comment by HowYeahYu** [comment]
> you can simply run
> 
> ```
> docker run --rm -p 9114:9114 justwatch/elasticsearch_exporter:1.1.0rc1 --es.uri= ...
> ```
> please note that `latest` points to the latest stable version, which is 1.0.2. Here the port is 9118 and the commandline arguments are prefixed with single dashes. I encourage you to try the release candidate though (as done in the example above)

It's working now. Thank you so much.
