### ISSUE TITLE
Still passwords in WARN log file or stdout

### ISSUE THREAD

**Issue by Kuckkuck** [justwatchcom/elasticsearch_exporter#234]
Hi,

this time on level WARN there is still the connect string with user+pw in stdout, Could this be removed?

`level=warn ts=2019-03-15T08:38:11.97457457Z caller=cluster_health.go:284 msg="failed to fetch and decode cluster health" err="failed to get cluster health from http://elasticsearch.bla:9200/_cluster/health: Get http://bla:bla@elasticsearch.bla:9200/_cluster/health: dial tcp 100.127.153.186:9200: connect: connection refused"`

Thanks a lot.

**Comment by zwopir** [comment]
I'll fix it. Thanks for reporting!

**Comment by zwopir** [comment]
this is fixed in master and the latest RC `1.1.0rc1`
