### ISSUE TITLE
Kubernetes deployment: runAsUser is useless

### ISSUE THREAD

**Issue by bquartier** [justwatchcom/elasticsearch_exporter#236]
The example of kubernetes deployment adds a runAsUser: 1000 in the pod [definition](https://github.com/justwatchcom/elasticsearch_exporter/blob/master/examples/kubernetes/deployment.yml#L19).

This seems useless and prevent the deployment from running out of the box in Kubernetes distribution that have stricter security requirements like OpenShift. Would it be possible to remove this constraint?
Same is true for the kubernetes chart; it doesn't run out of the box in openshift because of the runAsUser=1000.

**Comment by bquartier** [comment]
Hi @zwopir,
We are debating the necessity for runAsUser in the k8s chart repository here:
https://github.com/helm/charts/pull/12627

Could you please provide your view about why runAsUser=1000 is needed?

Thank you.
Benoît

**Comment by zwopir** [comment]
Hi @bquartier,

it's not needed and I'll remove it from the k8s yml. It's there for historical reasons
