### ISSUE TITLE
New stable release?

### ISSUE THREAD

**Issue by bquartier** [justwatchcom/elasticsearch_exporter#237]
The latest stable release is from January 2018 (1.0.2).
1.14 and 1.1 only exists in rc (1.0.4rc1 and 1.1.0rc1).

Do you plan a new stable (not rc) release?

(I don't really care using a rc, but I would like to add the es.ssl-skip-verify option to the helm chart. I think it makes sens to only add options that are part of a stable release to a stable helm chart).

**Comment by TheMeier** [comment]
I general it would be much nicer to have more releases with fewer changes. How about considering adding maintainers?

**Comment by zwopir** [comment]
Hi @bquartier and @TheMeier,

first of all: thanks for your help here. I absolutely agree that it's better to have more frequent but smaller releases.
I'd love to have more maintainers here and hope to find some time to set up the required infrastructure (build job, organizational things like slack channel or whatever).

If you are interested to help as a maintainer, please send me an email to christoph.oelmueller@justwatch.com

**Comment by TheMeier** [comment]
@zwopir any news here? It's nearly 2 month since the last update and already another 30 commits after the last rc-version was tagged. Can't you just tag 1.1.0rc1 as 1.1.0, what is stopping you from doing that?

**Comment by dannyk81** [comment]
@zwopir just a gentle ping here.

I think 1.1.0rc1 should be safe to release?

**Comment by zwopir** [comment]
Hi @dannyk81,

yes, 1.1.0rc1 should be fine. I'm currently on holidays. Back on the 31.7. to release a stable candidate. Sorry for the delay

**Comment by zwopir** [comment]
I'm really sorry it took me so long. Here we are: https://github.com/justwatchcom/elasticsearch_exporter/releases/tag/v1.1.0

**Comment by tetianakravchenko** [comment]
FYI: here is a helm/charts PR to support latest release https://github.com/helm/charts/pull/16096

**Comment by zwopir** [comment]
nice, thank you!
