### ISSUE TITLE
Why metrics elasticsearch_cluster_health_up and elasticsearch_node_stats_up don't have the cluster_name and node_name info?

### ISSUE THREAD

**Issue by Gareer** [justwatchcom/elasticsearch_exporter#239]

**Comment by zwopir** [comment]
Hi @Gareer,

they can't. The metric indicates if the API call succeeded. With no response from the API it's hard to tell the cluster_name etc. Exporting the labels only in the success case creates metrics with different label sets which is a no-go in prometheus (and even panics iirc)

**Comment by Gareer** [comment]
OK, got it, thanks!
