### ISSUE TITLE
Not getting all the index based metrics

### ISSUE THREAD

**Issue by biparida** [justwatchcom/elasticsearch_exporter#240]
I am using the 10.4rc1/20180817 release candidate of the elasticsearch-exporter.

I have tried adding the option "-es.all" ("-es.indices"), but i couldn't get any metrics based on the index (e.g. documents per index or any similar metrics).

Do I need to enable anything else?

Requesting you to have a look at it and kindly let me know how to proceed further.

**Comment by biparida** [comment]
@zwopir Any suggestions for this issue?

**Comment by zwopir** [comment]
Hi @biparida,

could you please try the latest RC (1.1.0rc1) with
```
./elasticsearch_exporter --es.uri http://<your-es-node>l:9200 --es.all --es.indices
```
and curl the endpoint on `http://localhost:9114/metrics`.

**Comment by biparida** [comment]
Hi @zwopir,

I am getting the below metrics. I am looking for metrics with segregation of individual metric.

elasticsearch_index_stats_indexing_index_total

<img width="1631" alt="Screen Shot 2019-05-21 at 1 57 38 AM" src="https://user-images.githubusercontent.com/23699017/58050149-31945580-7b6c-11e9-89bb-519adc73c8b8.png">
<img width="1625" alt="Screen Shot 2019-05-21 at 1 58 01 AM" src="https://user-images.githubusercontent.com/23699017/58050150-31945580-7b6c-11e9-9d15-7ec9d78fffbb.png">


Thanks
Bijay

**Comment by zwopir** [comment]
Hi Bijay,

I don't quite understand what your question is, but I noticed that the index in the above query is `logstash-2019.04.20` while it is `logstash-2019.05.20` in the second one

**Comment by biparida** [comment]
Thanks Christoph, getting them after adding--es.indices. I want to get the sum of the counts dynamically.

Something like sum(elasticsearch_index_stats_indexing_index_total{cluster="$cluster",index="$index_name"})

But, I can't pass the dynamically, something like `logstash-*`

But, the below query works.
sum(elasticsearch_index_stats_indexing_index_total{cluster="$cluster",index="logstash-2019.05.22"})

**Comment by zwopir** [comment]
you can use regexp label matching (see https://prometheus.io/docs/prometheus/latest/querying/basics/#instant-vector-selectors) for the index label. Something like `sum(elasticsearch_index_stats_indexing_index_total{cluster="$cluster",index=~"logstash-2019.*"})` or whatever regexp fits your requirements

**Comment by biparida** [comment]
Thanks a lot. In the mean time I was able to figure out. I will wait for the latest stable release to be available to use it. Closing the issue.

sum(elasticsearch_index_stats_indexing_index_total{cluster=~"$cluster",index=~".*"}) by (index)
