### ISSUE TITLE
Startup not failing if port is already in use

### ISSUE THREAD

**Issue by slovdahl** [justwatchcom/elasticsearch_exporter#241]
While trying to write a systemd unit for elasticsearch_exporter, I noticed that startup doesn't fail if the process can't bind to the requested port.

A line is logged (`level=error ts=2019-05-02T08:28:32.578028364Z caller=main.go:190 msg="http server quit" err="listen tcp 0.0.0.0:9114: bind: address already in use"`), but the process just keeps running. In my opinion, this is a bit unexpected behaviour. Instead, the process should exist with a non-zero status code.

Is this intentional, or just an oversight?

**Comment by zwopir** [comment]
that's a bug

**Comment by slovdahl** [comment]
Awesome, thank you, that was quick! :bowing_man:
