### ISSUE TITLE
Date parse error

### ISSUE THREAD

**Issue by pramodShehan5** [justwatchcom/elasticsearch_exporter#247]
Hi,

Here I am using this, I am getting this error,

```
level=error ts=2019-05-15T06:36:01.949096522Z caller=clusterinfo.go:171 msg="failed to retrieve cluster info from ES" err="parsing time \"\"Unknown\"\" as \"\"2006-01-02T15:04:05Z07:00\"\": cannot parse \"Unknown\"\" as \"2006\""

```

**Comment by zwopir** [comment]
Hi @pramodShehan5,

thanks for bringing this up. It seems like the ES endpoint on `http://<es_address>:9200/` (or whatever port) returns the json field `build_date` with a value of `Unknown`. The code expects a `time.Time` there. 

Could you verify this by pasting the output of the above output here? Once it's verified, I can fix the code

I wonder where this value is coming from. Is your ES a custom build one?

**Comment by pramodShehan5** [comment]
Hi , 

I am using elassandra cluster. Not native elasticsearch.

**Comment by zwopir** [comment]
ah, ok. Can you curl the elassandra cluster on `/` end send me the output, please?!

**Comment by pramodShehan5** [comment]
I used **curl localhost:9200/**

```
{
  "name" : "172.11.0.9",
  "cluster_name" : "documents",
  "cluster_uuid" : "59ef5fd6-8c3a-4e01-9f41-c4b1da367a7e",
  "version" : {
    "number" : "6.2.3",
    "build_hash" : "Unknown",
    "build_date" : "Unknown",
    "build_snapshot" : true,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

```

**Comment by zwopir** [comment]
perfect, so the problem only exists for the `build_date` field as `Unknown` is a perfectly fine `build_hash` ;)

**Comment by zwopir** [comment]
Hi, can you build from source from the branch `bugfix/clusterinfo_parsing_error` and try again. The branch contains the bugfix

**Comment by pramodShehan5** [comment]
it is working now, but you should change **clusterinfo.go** also.

```
**line 128 -** res.Version.BuildDate,


```

**Comment by zwopir** [comment]
done

**Comment by pramodShehan5** [comment]
Thanks a lot

**Comment by pramodShehan5** [comment]
Hi again,

I need to override elasticsearch  api using **-es.uri .** 

So I added **CMD** to my dockerFile.
```
CMD  -es.uri="http://elasticsearch:9200"

```
But it is not overriding. Still use  **localhost:9200**

**Comment by zwopir** [comment]
which version are you using? Please not that the latest master as well as the `1.1.0rc1` (and all upcoming versions) are using posix style cmdline parameters ( `--es.uri`)

**Comment by pramodShehan5** [comment]
Yes, I am using 1.1.0rc1. I have attached my git log below. If I add **CMD** to **dockerFile** like this I got an error called **" Unknown flag: es.all".** when I am trying to build docker.

```
CMD --es.all=true

```


![git log](https://user-images.githubusercontent.com/9468378/57847438-1637ec00-77f4-11e9-9af0-7751f5220446.png)

**Comment by zwopir** [comment]
this is most certainly not a problem with the exporter itself. Can you please post your `Dockerfile` here?

**Comment by pramodShehan5** [comment]
Hi, I am also not thinking it is as a problem,

**FROM golang:1.9

RUN apt-get update -y

ADD . /go/src/github.com/justwatchcom/elasticsearch_exporter
WORKDIR /go/src/github.com/justwatchcom/elasticsearch_exporter

# build
RUN go build -o /bin/exporter *.go

RUN cp /go/src/github.com/justwatchcom/elasticsearch_exporter/docker-entrypoint.sh /bin/docker-entrypoint.sh

CMD --es.all=true

EXPOSE      9114
ENTRYPOINT  ["/bin/docker-entrypoint.sh"]**

**Comment by zwopir** [comment]
must be an issue with your Dockerfile/entrypoint setup. Can't help here, as we do provide a docker setup + prebuild containers and I don't know the content for `docker-entrypoint.sh`
