### ISSUE TITLE
SHA256 sums of binary releases missing

### ISSUE THREAD

**Issue by ksaio** [justwatchcom/elasticsearch_exporter#248]
Hi,

It would be lovely if sha265 sums was released with binaries like they do in the official repos like node_exporter (see https://github.com/prometheus/node_exporter/releases)

Thanks.

**Comment by zwopir** [comment]
will add them to the next release

**Comment by zwopir** [comment]
the latest release now includes a `sha256sums.txt` file that contains the sha265 sums of the release tarballs. See https://github.com/justwatchcom/elasticsearch_exporter/releases/tag/v1.1.0
