### ISSUE TITLE
All *_up metrics return 0

### ISSUE THREAD

**Issue by KristianZH** [justwatchcom/elasticsearch_exporter#250]
Describe the bug
Hi. I noticed that the all *_up metrics return 0. Is it mean that the last scrape was unsuccessful and what might be the reason for this

What happened: 
elasticsearch_index_stats_up,      |
elasticsearch_cluster_health_up  |  =>  All of them return 0
elasticsearch_node_stats_up       |

What you expected to happen:
I think that the value for successful scrape is 1, so i expect to get 1 from them metrics, not 0.

How to reproduce it (as minimally and precisely as possible):
elasticsearch-oss 6.7.1
elasticseearch-exporter 1.0.2

**Comment by zwopir** [comment]
apparently you solved the problem. The `_up` metrics reflect success/failure of the corresponding elasticsearch HTTP API calls. The logs provide further details on failures.
