### ISSUE TITLE
"elasticsearch_indices_docs" metric is missing

### ISSUE THREAD

**Issue by rolindroy** [justwatchcom/elasticsearch_exporter#251]
Hello,

I have deployed elasticsearch_exporter on K8s cluster to send ES metrics to Prometheus. I could see some of the metrics are missing. I have enabled "es.indices=true" to query stats for all indices in the cluster. But "elasticsearch_indices_docs" is missing in the metric list.

 ```
     containers:
        - name: elasticsearch-exporter
          image: "justwatch/elasticsearch_exporter:1.0.2"
          imagePullPolicy: IfNotPresent
          command: ["elasticsearch_exporter",
                    "-es.uri=elasticsearch-logging:9200",
                    "-es.all=true",
                    "-es.indices=true",
                    "-es.timeout=30s",
                    "-web.listen-address=:9108",
                    "-web.telemetry-path=/metrics"]
```

**Comment by zwopir** [comment]
can you please check if the problem still occurs if you use the version `1.0.4rc1`?!

**Comment by rolindroy** [comment]
@zwopir I was able to fix this issue by modifing  "`-es.uri`" with `http` tag as prefix.
`-es.uri=http://elasticsearch-logging:9200`

Thanks for your time.
