### ISSUE TITLE
[SNAPSHOTS] Get info of each snapshot

### ISSUE THREAD

**Issue by luarx** [justwatchcom/elasticsearch_exporter#255]
Could I obtain information of a specific snapshot like when I use this endpoint `/_snapshot/[REPO_NAME]/[SNAPSHOT_NAME]`?

The reason is because:
- I want to know which indices has each snapshot OR which indices has the last snapshot
Because as each day I generate a new index like (logstash_2019-06-01) I want to know if the last snapshot contains that index. If it doesn't contain that maybe something is misconfigured

**Comment by zwopir** [comment]
Hi @luarx,

no, this isn't implemented. I'd rather do the consistency check immediately after creating the backup as handling with templated checks (like creating the index name from the current date) can't be done nicely in promQL.
