### ISSUE TITLE
[SNAPSHOTS] Get state value of the last executed snapshot

### ISSUE THREAD

**Issue by luarx** [justwatchcom/elasticsearch_exporter#256]
I want to know `"state" : ""` value of the last executed snapshot to fire an alert if it is not 'SUCCESS'

I think that this value could be obtained from `/_snapshot/[REPO_NAME]/[SNAPSHOT_NAME]`

**Comment by zwopir** [comment]
doesn't `elasticsearch_snapshot_stats_snapshot_number_of_failures` (# HELP elasticsearch_snapshot_stats_snapshot_number_of_failures Last snapshot number of failures) include this information?
