### ISSUE TITLE
failed to get cluster health

### ISSUE THREAD

**Issue by acarsercan** [justwatchcom/elasticsearch_exporter#258]
Hi,

I've enabled the exporter in a k8s cluster using the helm chart and set the values as such:

```    es:
          uri: http://172.26.156.36:9200

```

```    service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9108"
```

Yet I'm seen the following errors:

```
msg="failed to fetch and decode index stats" err="failed to get index stats from http://172.26.156.36:9200/_all/_stats: Get http://172.26.156.36:9200/_all/_stats: EOF"
```

Any ideas?

**Comment by zwopir** [comment]
can you post the results of a curl to the endpoint `http://172.26.156.36:9200/_all/_stats`? It's seems the exporter is receiving an incomplete/malformed answer from the ES.

**Comment by acarsercan** [comment]
I was doing it all wrong, installed the exporter on the VM outside k8s and asked prometheus to scrape on that port
