### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by jakubgs** [justwatchcom/elasticsearch_exporter#259]
It would be nice to have a `/health` endpoint that returns just `OK` when everything is running fine.

**Comment by zwopir** [comment]
Hi @jakubgs,

there's a default handler implemented already. It's used every time a path is requested that's not `/metrics` (or what's configured via `web.telemetry-path`). So `/health` used that default handler as well.

It returns the following content with a HTTP 200:
```<html>
			<head><title>Elasticsearch Exporter</title></head>
			<body>
			<h1>Elasticsearch Exporter</h1>
			<p><a href="/metrics">Metrics</a></p>
			</body>
</html>```
If the default handler is up, all internal collectors have been initialized, so it reflects the aliveness of the exporter

**Comment by jakubgs** [comment]
Yeah, that works, true, and that's what I'm using right now, but it also puts a bunch of HTML into my healthecks in my [Consul](https://www.consul.io/) UI. I was hoping for something that just returns a minimal `OK`.

This isn't in any way crucial, it's just nice to have. Thanks for responding, close this if you think this isn't necessary.

**Comment by zwopir** [comment]
implemented and released in https://github.com/justwatchcom/elasticsearch_exporter/releases/tag/v1.1.0

**Comment by jakubgs** [comment]
Thank you!
