### ISSUE TITLE
Create new docker images and push them to the registry

### ISSUE THREAD

**Issue by metalmatze** [justwatchcom/elasticsearch_exporter#26]
We need to build new docker images and push them to hub.docker.com.
Maybe we should also evaluate quay.io because prometheus themselves are pushing there too.

**Comment by jeanlouisboudart** [comment]
Any progress on this ? Where could we find those docker images ?

**Comment by metalmatze** [comment]
Nothing so far, sorry. We didn't release anything ourselves yet and that's why we still don't have any docker images.

**Comment by jeanlouisboudart** [comment]
Looks like the state of master branch is already usable. Even if there plenty of good ideas  / documentation/dashboards/examples to provides like you did on sql_exporter, releasing it would allow users / community to give you feedback ( see the release early, release often paradigm => https://en.wikipedia.org/wiki/Release_early,_release_often).

You could then  build incrementally documentation features with a better feedback loop.

My 2 cents.

Meanwhile is there anything we can do to help you ?

**Comment by dominikschulz** [comment]
Released 0.3.1. Sorry for the delay.

**Comment by lhoss** [comment]
### in short:
Is there now a docker-hub or quai.io repos containing latest builds? ( I couldn't find, nor in the Doc, nor googling)

### longer story:
after 1 hour of research to find the 'best' avalable elasticsearch_exporter *and* up2date public docker images for it, I found >3 exporters (interestingly in 3 diff. major prg-langs java, python and go (this one!) )
but disappointed by not finding either a dockerhub nor quai.io repos that contains the latest builds for this/justwatchcom one.
A quick web search yielded 2 docker-hub repositories of images, coming from 2 different (+diverging) forks of this exporter:
* https://hub.docker.com/r/lowstz/elasticsearch_exporter/
* https://hub.docker.com/r/echocat/elasticsearch_exporter/

and on quai.io found following image, based on this one, but strangely has latest tag 0.5.0:
https://quay.io/repository/traum-ferienwohnungen/elasticsearch_exporter/image/1dc406bcc9dbe89cf4481a3ae6c411bb58e3ed9c6d1666cf2c9b85df3aac8ba0

**Comment by dominikschulz** [comment]
We push our builds to `justwatch/elasticsearch_expprter`. It's linked from the README. We'll try to make this clearer.
