### ISSUE TITLE
latest tag on Docker Hub still uses port 9108

### ISSUE THREAD

**Issue by adrianjord** [justwatchcom/elasticsearch_exporter#262]
The latest tag hasn't been updated in over a year on Docker Hub, it makes it very confusing that the documentation does not line up on GitHub and Docker Hub.

**Comment by ZVilusinsky** [comment]
Yeah, just spent some time dealing with this. This should really be included at the top of the readme.

**Comment by zwopir** [comment]
fixed in https://github.com/justwatchcom/elasticsearch_exporter/releases/tag/v1.1.0 and the corresponding docker hub release
