### ISSUE TITLE
Example Role for Elastic User

### ISSUE THREAD

**Issue by kskewes** [justwatchcom/elasticsearch_exporter#278]
To verify deployment and metrics we have been using the default `superuser` level `elastic` user.
We would like to follow the principle of least privilege and restrict the exporter user to just the permissions required.

It would be great if we can spec out the permissions required for `elasticsearch_exporter` and write up an example `role`.

Given the release of many security features into the OSS version with ES 7.0 it might be good enough to scope the role to ES 7.0+

ES 7.3 doc links:
- [Build in Users](https://www.elastic.co/guide/en/elastic-stack-overview/7.3/built-in-users.html)
- [Defining Roles](https://www.elastic.co/guide/en/elastic-stack-overview/7.3/defining-roles.html)
- [Privileges](https://www.elastic.co/guide/en/elastic-stack-overview/7.3/security-privileges.html)

Findings so far:

Setting | Privilege Required | Description
:---- | :---- | :----
exporter defaults | `cluster` `monitor` | All cluster read-only operations, like cluster health and state, hot threads, node info, node and cluster stats, and pending cluster tasks. |
es.cluster_settings | `cluster` `monitor` | 
es.indices | `indices` `monitor` (per index or `*`) | All actions that are required for monitoring (recovery, segments info, index stats and status) 
es.indices_settings | `indices` `monitor` (per index or `*`) | 
es.shards | not sure if `indices` or `cluster` `monitor` or both | 
es.snapshots | `cluster:admin/snapshot/status` and `cluster:admin/repository/get` | [ES Forum Post](https://discuss.elastic.co/t/permissions-for-backup-user-with-x-pack/88057)

Any feedback or suggestions most welcome.

**Comment by zwopir** [comment]
Hi Karl,

would a list of used endpoints help to narrow down the role permissions needed for the exporter?

**Comment by kskewes** [comment]
Thanks Christoph. I ended up looking through the code to find the endpoints.
I think the above list is reasonable as it looks like none of these permissions provide access to the raw data (docs).
Haven't tested out what happens if restrict permissions to a single index only.

I guess we could either close this issue or put something in the README?

**Comment by zwopir** [comment]
Hi Karl,

I added your findings to the documentation. Thanks for figuring out the required security privileges

**Comment by bigman3** [comment]
@zwopir example role for monitoring the entire cluster, ES 7.16.2
 
```
{
  "cluster" : [
    "monitor",
    "monitor_snapshot"
  ],
  "indices" : [
    {
      "names" : [
        "*"
      ],
      "privileges" : [
        "monitor"
      ],
      "allow_restricted_indices" : true
    }
  ],
  "applications" : []
}
```

**Comment by mkoertgen** [comment]
Thank @bigman3 for the role definition. I could get this working using k8s secrets as documented here

- https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-users-and-roles.html#k8s_creating_custom_roles

Yet I still got 403-problems with parsing back indices_mappings

```
level=warn ts=2022-01-19T15:37:59.406846953Z caller=indices_mappings.go:175 msg="failed to fetch and decode cluster mappings stats" err="HTTP Request failed with code 403"
```

In case anyone stumbles upon this, I worked around this by setting helm values `es.indices_mappings=false`

**Comment by BapRx** [comment]
And if you do want to fetch indices mappings, you can add the index privilege `view_index_metadata` to your role.
cf. https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html#get-mapping-api-prereqs
