### ISSUE TITLE
Unable to find _nodes/_local/stats in ES 6.8.1

### ISSUE THREAD

**Issue by gretamosa** [justwatchcom/elasticsearch_exporter#283]
It generates the following error:

> level=warn ts=2019-08-21T10:17:09.719549221Z caller=nodes.go:1851 msg="failed to fetch and decode node stats" err="failed to get cluster health from http://localhost:27015/_nodes/_local/stats: Get http://localhost:27015/_nodes/_local/stats: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"

It's possible that you must change _nodes/local/stats by _nodes/stats ?

Regards,

**Comment by zwopir** [comment]
no, the endpoint is correct. It seems like a network issue, otherwise you won't see a `Client Timeout exceeded while awaiting headers`

**Comment by gretamosa** [comment]
Yes, you're right. I'll review it.

Thanks!
