### ISSUE TITLE
-es.uri is now --es.uri

### ISSUE THREAD

**Issue by remram44** [justwatchcom/elasticsearch_exporter#284]
I updated from 1.0.2 to 1.1.0 and `-es.uri` no longer works (it's `--es.uri`). The docker-compose section of the README should probably be updated, and perhaps a mention of this backwards-incompatible change be added somewhere too.

**Comment by zwopir** [comment]
yes, the docker-compose section is still on single-dashes. Fixed it. Thanks for the heads up.

The breaking change is documented in docker-hub and the release page
