### ISSUE TITLE
Feature Request: custom queries with time intervals

### ISSUE THREAD

**Issue by oylmz** [justwatchcom/elasticsearch_exporter#286]
Is custom queries with time intervals going to be supported anytime soon  like it's implemented in https://github.com/justwatchcom/sql_exporter ? 
It would be a great feature to have ES queries with dynamic parameters can be run against ES based on a given interval.

queries.yaml can be examined in https://github.com/wrouesnel/postgres_exporter

**Comment by zwopir** [comment]
Hi @oylmz,

this feature is not planned, as discussed in #275. I do understand that this is a frequently requested feature, but it is simply out of the scope of this exporter.

**Comment by oylmz** [comment]
Thanks for the clean explanation in #275 @zwopir
