### ISSUE TITLE
Dashboard problem with multiple exporters

### ISSUE THREAD

**Issue by hangxie** [justwatchcom/elasticsearch_exporter#289]
Dashboard does work properly when we run 2 exporters targeting the same ES instance, as all metrics are reported twice (with different instance label though)

**Comment by hangxie** [comment]
Some of the dashboard can be fixed by https://github.com/hangxie/elasticsearch_exporter/commit/553a7f0f1cb9b1d0a2d48ecbde5889b4d9365f17, but not all of them. I believe the best way is to introduce `instace` to the dashboard so and apply `instance="$instance"` to all related dashboards.

**Comment by dcwangmit01** [comment]
Something like this: 
https://grafana.com/api/dashboards/6483/revisions/2/download

**Comment by zwopir** [comment]
why would you run two exporters on the same target in the first place? I don't see this is a use case we need to support. If you still to do it for whatever reason, just include the instance label in all the metrics

**Comment by slovdahl** [comment]
AFAICT, this is also a problem if more than one node in a cluster has an exporter, and all those exporters are scraped. I fully understand why the graphs don't work in that case, as the Prometheus query console shows that 3 results are returned:

![image](https://user-images.githubusercontent.com/1417619/71616718-5c459280-2bc0-11ea-87b4-7e6553a69e6e.png)

This is what the Grafana dashboard looks like:

![image](https://user-images.githubusercontent.com/1417619/71616687-34eec580-2bc0-11ea-8f28-327e0f15a850.png)

Any ideas how to work around this?

**Comment by slovdahl** [comment]
I also realized that the "Documents indexed" is lying in this case. It's the sum of documents from all 3 exporters, i.e. 3 times the number of actual documents in the cluster.
