### ISSUE TITLE
elasticsearch_up metric

### ISSUE THREAD

**Issue by ralberto** [justwatchcom/elasticsearch_exporter#31]
I'm using elasticsearch_up metric to display elasticsearch status in a grafana dashboard. However, for reasons that I do not understand, this metric value is constantly switching from 0 to 1 and back to 0 IF queried using the prometheus interface. Accessing the exporter metrics endpoint directly, elasticsearch_up metric  allways returns the value 1!

I'm using haproxy exporter's haproxy_up metric and it works without any problem. I have no ideia what's causing this behavoir.

Any idea what might be happening here?

**Comment by metalmatze** [comment]
I think that might not be a problem of the exporter itself. I just looked into our timeline for `elasticsearch_up` and it's always `1` for the past week. How often is it switching between `0` and `1` for you?
