### ISSUE TITLE
Prometheus not scraping all metrics from endpoint

### ISSUE THREAD

**Issue by MrPink** [justwatchcom/elasticsearch_exporter#312]
This maybe misconfigured on my end but I'm not seeing all the metrics in the Prometheus UI, I'm missing the majority of `elasticsearch_cluster_health_*`. If I port forward and look at `/metrics` I can see the metrics in there.

Any pointers appreciated

**Comment by MrPink** [comment]
I managed to duplicate service metric endpoints and one wasn't working

closing ticket

**Comment by anilkumar000** [comment]
facing the issue but didn't understand the resolution. Any quick suggestions appreciated.
