### ISSUE TITLE
first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by artem-dronov** [justwatchcom/elasticsearch_exporter#319]
The problem is not only in the docker on the host, when launched through the system unit, such an error:
`elasticsearch_exporter[16405]: level=error ts=2020-01-27T07:29:08.675384105Z caller=main.go:90 msg="failed to parse es.uri" err="parse \"10.*.20.*:9200\": first path segment in URL cannot contain colon"`
Unit:

```
[Unit]
Description=Prometheus Elastic Exporter
#Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=root
Group=root
#User=elasticsearch-exp
#Group=elasticsearch-exp
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/elasticsearch_exporter --web.listen-address="212..225.:9114" --es.uri="http://10..20.:9200"

SyslogIdentifier=elasticsearch_exporter
Restart=always
RestartSec=1

PrivateTmp=yes
ProtectHome=yes
NoNewPrivileges=yes

ProtectSystem=full

[Install]
WantedBy=multi-user.target

```
If you execute directly through the command line, then everything works:

`/usr/local/bin/elasticsearch_exporter --web.listen-address="212.*.225.*:9114" --es.uri="10.*.20.*:9200"
`
`level=info ts=2020-01-27T07:33:57.410669859Z caller=clusterinfo.go:200 msg="triggering initial cluster info call" level=info ts=2020-01-27T07:33:57.410799832Z caller=clusterinfo.go:169 msg="providing consumers with updated cluster info label" level=info ts=2020-01-27T07:33:57.413413551Z caller=main.go:148 msg="started cluster info retriever" interval=5m0s level=info ts=2020-01-27T07:33:57.413650816Z caller=main.go:188 msg="starting elasticsearch_exporter" addr=212.*.225.*:9114`
System: Debain jessie

What could be the problem?

**Comment by zwopir** [comment]
not sure why it should work directly and not via systemd, but to me the ES URL seems to be the problem. Can you try prepending the URL with `http://` (or `https` if it's a secure connection)

**Comment by artem-dronov** [comment]
> not sure why it should work directly and not via systemd, but to me the ES URL seems to be the problem. Can you try prepending the URL with `http://` (or `https` if it's a secure connection)

Thanks for the comment, but I already did this experiment and forgot to put it back, put it back in place, but it didn't work

**Comment by zwopir** [comment]
can't help you much here without knowing what values you put into the parameter `--es.uri`. It doesn't make much sense to be inaccurate with redacting/copying the most relevant information ;) )
Nevertheless two more hints:
 - make sure there's no shell interpolation going on before passing the parameter to the exporter (single quotes vs. double quotes)
 - the URL is parsed with the go `net/url` package. There's been quite some confusion about how URLs are parsed. See https://github.com/golang/go/issues/18824. Make sure to also read https://godoc.org/net/url#Parse

**Comment by erdong** [comment]
I have the same problem ，I use the systemd control  elasticsearch_exporter 。

Through many attempts it can works.

In systemctl elasticsearch_exporter service Unit Can't appear quotes （"）

The sample：

```
...

[Service]
Type=simple
User=root
Group=root
#User=elasticsearch-exp
#Group=elasticsearch-exp
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/elasticsearch_exporter --web.listen-address=212..225.:9114 --es.uri=http://10..20.:9200
...


```


But in elasticsearch_exporter help 


```
      --web.listen-address=":9114"
                             Address to listen on for web interface and telemetry.
      --es.uri="http://localhost:9200"
                             HTTP API address of an Elasticsearch node.
```
I refer to this help documentation,  elasticsearch_exporter unable to start .
