### ISSUE TITLE
Counter decreases should not occur

### ISSUE THREAD

**Issue by craigfurman** [justwatchcom/elasticsearch_exporter#327]
I've noticed counter decreases for the metric `elasticsearch_indices_indexing_index_total`. We are running with `-es.all` to scrape a whole cluster from one external exporter. 

You can see a small decrease here:

<img width="1448" alt="Screenshot 2020-03-13 at 16 16 23" src="https://user-images.githubusercontent.com/4772216/76759319-599c1780-6783-11ea-9a6f-6d56dc0bc607.png">

This looks like a momentary glitch, as the metric appears to resume its almost uniform linear rate of increase from where it was projected to be at if the dip had never occurred.

Prometheus interprets this as a counter reset. Functions such as `rate` assume that the counter has increased from zero to the first lower absolute value it sees, leading to rate spikes whose size is determined by the absolute value of the counter. These can be orders of magnitude higher than they should be:

<img width="1447" alt="Screenshot 2020-03-13 at 16 13 45" src="https://user-images.githubusercontent.com/4772216/76759444-9536e180-6783-11ea-9545-95a60abab2d0.png">

This doesn't really look like a bug in the exporter, as it appears to simply set the metric from the response it gets from `/_nodes/stats`. It's possible that elasticsearch is serving stale data. If that's the case, this might be fixable by not updating counters (all, not just index_total) to values lower than they are already set to. The rate of such counters will be zero for the period in which a lower value has been returned by elasticsearch, but that error should usually be smaller than one based on the absolute value of a counter.

What do you think of this idea? Would you be interested in a PR that implements this?

**Comment by SuperQ** [comment]
I don't think there's a lot the exporter can do for us in this case. It very much seems like a bug in Elastic.

Even if we have some kind of tracking in the exporter, it's still possible to restart the exporter between scrapes and have no tracking data to go on and return a reset counter like this.

**Comment by craigfurman** [comment]
Agreed, there's not much the exporter can really do other than report what the elastic node stats API gives it. We can use `deriv` instead of `rate` to avoid a false counter reset amplifying the spikes.

**Comment by suprememoocow** [comment]
Note for anyone considering using `deriv` in future: 

If you're using short ranges, like `1m`, deriv is probably fine, but if you're using long durations, like `6h`, the likelihood of the `deriv` hitting an actual reset increases, leading to this approach being quite inaccurate, since the `deriv` will not treat the resets as resets, possibly leading to negative values if the value after the reset is higher than before. Even with a `clamp_min` you loose all data for the entire period.
