### ISSUE TITLE
what is the scraping interval?

### ISSUE THREAD

**Issue by lechen26** [justwatchcom/elasticsearch_exporter#340]
Hi

im trying to use this exporter to scrape metrics from external elasticsearch server (elastic.co)
there is the comment regarding 'scraping interval too tight that might be updated' but its not defined anywhere what is this interval and how to change it.

i see that it fetches data from the cluster 'on every scrape'. what does it mean? 
maybe im missing some basic logic

thanks

**Comment by lechen26** [comment]
is it 10s? i saw in another repo that there is ServiceMonitor.interval parameter

**Comment by zwopir** [comment]
Hey lechen26,

prometheus is a pull based system, so the scrape interval is configured in your prometheus config
