### ISSUE TITLE
unsupported protocol scheme \"\" Error

### ISSUE THREAD

**Issue by jividijuvent** [justwatchcom/elasticsearch_exporter#369]
Hi, I installed the exporter on the new elastic node, and got this error:
failed to get cluster info" err="Get http/192.168.1.228:9200: unsupported protocol scheme \ " \ "
I defined the es server with --es.uri=http//192.168.1.228:9200, same as other es nodes that I am already monitoring with the same exporter,
any idea what's the problem?

**Comment by bartjolenovation** [comment]
just to make sure: did you define it as http//192.168.1.228:9200 or http://192.168.1.228:9200 (colon after http added)?

**Comment by jividijuvent** [comment]
> just to make sure: did you define it as http//192.168.1.228:9200 or http://192.168.1.228:9200 (colon after http added)?

Oh man, what a ridiculous mistake, thank you, that's the problem.
