### ISSUE TITLE
how to distinguish two nodes on the same host

### ISSUE THREAD

**Issue by wangxiangyu** [justwatchcom/elasticsearch_exporter#46]
hi
   if two nodes are on the same host, the metrics exposed both use the ip as the node name.
  eg:
```
elasticsearch_thread_pool_active_count{cluster="ops-es",node="172.18.20.57",type="bulk"} 0 
```

so how to distinguish metrics between two nodes?

**Comment by dominikschulz** [comment]
Nice find. Never tried this. We're planning to add the node name as a label in the future.

**Comment by wangxiangyu** [comment]
@dominikschulz  another advise 
```
elasticsearch_cluster_health_status_is_green{cluster="ops-es"} 0
```
We want to know if the cluster is yellow or red. Only alert if the cluster is red.

**Comment by yackushevas** [comment]
@wangxiangyu jmcarp added cluster health state to report 0,1,2 - https://github.com/justwatchcom/elasticsearch_exporter/commit/9fbe08720989bf0e8fe274ab24677aaf205bfae3
