### ISSUE TITLE
Measure ElasticSearch API timeouts / Check elasticsearch_up

### ISSUE THREAD

**Issue by dominikschulz** [justwatchcom/elasticsearch_exporter#48]
In some cases the `elasticsearch_up` metric didn't work as expected.

We need to make sure this essential metric is working as expected.

**Comment by lhoss** [comment]
related to https://github.com/justwatchcom/elasticsearch_exporter/issues/31 ?

**Comment by dominikschulz** [comment]
@metalmatze Do you think we still need to address this after the rewrite?
