### ISSUE TITLE
tutorial on how to start from scratch

### ISSUE THREAD

**Issue by esseti** [justwatchcom/elasticsearch_exporter#56]
Hello, 

I've several nodes running elastic, and I would like to install the exporter on each node.

Now, I've installed GO, downloading the package and running `tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz` adding `export PATH=$PATH:/usr/local/go/bin` as said here https://golang.org/doc/install

Then, following the readme i run `go get -u github.com/justwatchcom/elasticsearch_exporter` which ends without saying anything (is that fine?).

And, when I try to run `elasticsearch_exporter --help` i get a `command not found` . 

what's the problem? i'm quite new to go and how it works..

**Comment by dominikschulz** [comment]
The easiest way to get started would be to run it in Docker.

Currently we don't provide binary releases, but we'll try to do so in the future.

**Comment by esseti** [comment]
Is there any tutorial on how to run it with docker?

my current problem is that I run a elastic cluster with kubernetes, so i should attach the exporter somewhere.

**Comment by dannyk81** [comment]
If I understood correctly, you are running Elastic inside Kubernetes cluster, so the nodes are deployed as Pods in K8s.

The easiest way to go about it, is to add the exporter as a container in these Pods.

If you share your K8s deployment manifest for Elastic, I can help suggest how to add the exporter.

**Comment by dominikschulz** [comment]
We're providing documentation and examples for docker, docker-compose and kubernetes as well as binary releases for most platforms.

This should cover these issues. Otherwise feel free to open another one.
