### ISSUE TITLE
failed to decode cluster health

### ISSUE THREAD

**Issue by thedodd** [justwatchcom/elasticsearch_exporter#68]
I am getting these warnings from the exporter when running against an elasticsearch cluster at version `5.4.1` with the prebuilt exporter [1.0.0-rc1.linux-amd64](https://github.com/justwatchcom/elasticsearch_exporter/releases/download/v1.0.0-rc1/elasticsearch_exporter-1.0.0-rc1.linux-amd64.tar.gz):
```
level=warn msg="failed to decode cluster health" err="json: cannot unmarshal number into Go struct field clusterHealthResponse.status of type string"
```

All of my configuration appears to be correct for the exporter. The elasticsearch cluster itself is healthy and in active use. I can query for the `/_cluster/health` manually using curl, and it returns the following:
```
{
    "active_primary_shards": 141,
    "active_shards": 348,
    "active_shards_percent_as_number": 100.0,
    "cluster_name": "<cluster_name>",
    "delayed_unassigned_shards": 0,
    "initializing_shards": 0,
    "number_of_data_nodes": 3,
    "number_of_in_flight_fetch": 0,
    "number_of_nodes": 4,
    "number_of_pending_tasks": 0,
    "relocating_shards": 0,
    "status": "green",
    "task_max_waiting_in_queue_millis": 0,
    "timed_out": false,
    "unassigned_shards": 0
}
```

Any ideas as to what the issue may be?

**Comment by zwopir** [comment]
Hi, 
we weren't able to reproduce the issue. Our ES /_cluster/health json looks similar to yours and the linux as well as the darwin binary ran fine.
Can you try to reproduce the bug with a self build binary?

**Comment by thedodd** [comment]
Ok, will do. Standby.

**Comment by thedodd** [comment]
Ok, when building `master:HEAD (63177b8)` from source, I get the same error. I built the code using go 1.6, I'm gonna upgrade to 1.8 (normally I would be running this in docker, but I didn't build this particular environment `:)). We'll see if that makes a difference.

Using go 1.6.
```bash
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Model name:            Intel(R) Xeon(R) CPU @ 2.60GHz
Stepping:              7
CPU MHz:               2600.000
BogoMIPS:              5200.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7
```

**Comment by zwopir** [comment]
that's strange. Basically whats happening in the code is this: https://play.golang.org/p/9gDO6MZrLl

In the play you can replace "green" with a number and reproduce the error from your description. So 

To see what the exporter really receives from ES you can patch collector/cluster_health.go like so (its around line 216)
```
diff --git a/collector/cluster_health.go b/collector/cluster_health.go
index 260bc6d..112f082 100644
--- a/collector/cluster_health.go
+++ b/collector/cluster_health.go
@@ -5,6 +5,9 @@ import (
        "net/http"
        "net/url"

+       "io"
+       "os"
+
        "github.com/go-kit/kit/log"
        "github.com/go-kit/kit/log/level"
        "github.com/prometheus/client_golang/prometheus"
@@ -212,7 +215,9 @@ func (c *ClusterHealth) Collect(ch chan<- prometheus.Metric) {
        }
        defer res.Body.Close()

-       dec := json.NewDecoder(res.Body)
+       tr := io.TeeReader(res.Body, os.Stdout)
+
+       dec := json.NewDecoder(tr)

        var clusterHealthResponse clusterHealthResponse
        if err := dec.Decode(&clusterHealthResponse); err != nil {
```
you then see the json on the console printed to stdout

**Comment by thedodd** [comment]
@zwopir thanks for the tip. Modifying the source as above and building with go 1.6 gives me the following output:

```
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "missing authentication token for REST request [/_cluster/health]",
        "header": {
          "WWW-Authenticate": "Basic realm=\"security\" charset=\"UTF-8\""
        }
      }
    ],
    "type": "security_exception",
    "reason": "missing authentication token for REST request [/_cluster/health]",
    "header": {
      "WWW-Authenticate": "Basic realm=\"security\" charset=\"UTF-8\""
    }
  },
  "status": 401
}
level=warn msg="failed to decode cluster health" err="json: cannot unmarshal number into Go value of type string"
```

The cluster's configuration hasn't changed since the upgrade of the exporter to `1.0.0-rc1`. Using the `es.ca`, `es.client-private-key` & `es.client-cert` arguments to perform the authentication to the cluster. Basic auth is enabled on the cluster as well. 

I did not see this issue using the older version of the `exporter`. Perhaps the auth protocol has been changed in this newer version.

**Comment by zwopir** [comment]
TLS setup hasn't changed, just been refactored. What has changed is the way we initialize our http client. It was
```
&http.Client{
 -			Transport: &http.Transport{
 -				TLSClientConfig: tlsClientConfig,
 -				Dial: func(netw, addr string) (net.Conn, error) {
 -					c, err := net.DialTimeout(netw, addr, timeout)
 -					if err != nil {
 -						return nil, err
 -					}
 -					if err := c.SetDeadline(time.Now().Add(timeout)); err != nil {
 -						return nil, err
 -					}
 -					return c, nil
 -				},
 -			},
```
the way of setting up timeout is deprecated here, so we changed to
```
httpClient := &http.Client{
		Timeout: *esTimeout,
		Transport: &http.Transport{
			TLSClientConfig: tlsConfig,
		},
	}
```
All of it shouldn't make a difference regarding basic auth.

To reproduce: can you please comment how you called the exporter and how you queried the _cluster endpoint via `curl`?

We'll have a look.
@metalmatze can you have a look too?!

**Comment by dominikschulz** [comment]
Thanks for reporting this. That's why we issued an rc1. Glad you tried it out.

Your output looks like the Basic Auth failed, that could possibly be an regression, but the code doing the actual request is (almost) the same as before.

We need to further investigate this. If you could try against an ES w/o basic auth that could help us narrow down this issue.

**Comment by zwopir** [comment]
http client initialization doesn't seem to matter: https://gist.github.com/zwopir/38d48ca3b76e62025074c664e76fa1d4

**Comment by dominikschulz** [comment]
I've added some tests against the _golden_ output of different ES versions (1.7, 2.4, 5.4) with and without basic auth.

The basic auth tests are failing right now, so either the tests are broken or (IMHO more likely) our handling of basic auth isn't working anymore. @metalmatze

**Comment by metalmatze** [comment]
Interesting, thanks for testing! I will look into that on Monday. :relaxed:

**Comment by dominikschulz** [comment]
nvm, my tests were flawed. Now they run fine even with basic auth.

**Comment by dominikschulz** [comment]
@thedodd So far we seem to be unable to reproduce your problem.
Could you please try without either basic auth or TLS to help us narrow down this issue?

**Comment by thedodd** [comment]
Will do.

**Comment by dominikschulz** [comment]
Here are the node stats tests: https://github.com/justwatchcom/elasticsearch_exporter/blob/master/collector/nodes_test.go

**Comment by thedodd** [comment]
@dominikschulz @metalmatze @zwopir I've resolved the issue. I'm ashamed to have opened this issue before trying this. All I had to do was embed the basic auth credentials in the URL for the elasticsearch instance as such: `https://<username>:<password>@<elasticURL>`. It is working as expected now.

Oy vey.

My expectations were that specifying the client cert and client private key would allow me to bypass the basic auth creds (or that a token would be generated and handled by this exporter as part of the initial handshake/connection). I was obviously wrong to an extent on that front.

Perhaps the only action item which really needs to come out of this to add some notes to the README about basic auth usage.

Thoughts?

*Also, we can close this issue now if you all don't see anything else which needs to be done.*

**Comment by metalmatze** [comment]
Good to hear.
I'm not really sure if we should add it to the README because it's just the normal way to use BasicAuth. But I don't see why we shouldn't. :thinking:

**Comment by thedodd** [comment]
That is the normal way to use basic, when there are no explicit command line options which can be given to specify credentials. E.G.: `curl` uses the `--user` flag, `httpie` uses the `--auth` flag &c.

The issue mostly stemmed from a misunderstanding on my behalf as to how this client was authenticating to the individual nodes. 

I'll open a quick PR to specify something simple in the README about this. You can accept it if you think it is logical.

Thanks again.
