### ISSUE TITLE
timestamp for log entries

### ISSUE THREAD

**Issue by Kuckkuck** [justwatchcom/elasticsearch_exporter#76]
Hi,

it would be nice to add timestamps to each log entry to get an idea, when the connection is failing. If you run the exporter in docker/kubernetes you have no idea, when the last connection was broken.
I have no time to dd this feature, but maybe you can added.

Thanks a lot and regards,

Olaf

**Comment by metalmatze** [comment]
Seems like I missed that somehow in the rewrite.
Made a PR. :+1:
