### ISSUE TITLE
Collect es.uri from ENV Variable.

### ISSUE THREAD

**Issue by ashoksahoo** [justwatchcom/elasticsearch_exporter#79]
Can we have an option of getting the es.uri from env.
The preference should be in the order
1) command line flag
2) env variable
3) default/locahost

**Comment by dominikschulz** [comment]
We'd like to keep this exporter consistent with others/official exporters. I've just checked a few of those and none seems to support getting options from ENV so I'd like to keep it as is for this exporter as well.

**Comment by ashoksahoo** [comment]
AWS recommends using credentials in Environment variable.
These are the few official exporters using Env Vars.
https://github.com/prometheus/mysqld_exporter#setting-the-mysql-servers-data-source-name
https://github.com/prometheus/cloudwatch_exporter#credentials-and-permissions
https://github.com/prometheus/consul_exporter#environment-variables

**Comment by dominikschulz** [comment]
Those are a little different. Apart from the mysqld_exporter - that is using it's config flags/env vars inconsistently - the exporters are not evaluating the env vars themselfes, but rather the upstream libs they use.

Feel free to start the exporter through an wrapper script that translates your env vars to command line args.
