### ISSUE TITLE
Document custom node exporter labels in grafana example

### ISSUE THREAD

**Issue by jmcarp** [justwatchcom/elasticsearch_exporter#81]
It looks like the sample dashboard uses metrics from the prometheus node exporter, like `node_memory_MemTotal`, that include the `cluster` label: https://github.com/justwatchcom/elasticsearch_exporter/blob/master/examples/grafana/dashboard.json#L156. This label isn't included in the node exporter by default, so I'm guessing you're adding custom labels in your `scrape_configs`. It would be useful to add a note describing this requirement and showing examples of how to add the custom labels, since several panels in the example dashboard won't work otherwise.

**Comment by zwopir** [comment]
Hi Joshua,

thanks for reporting the issue. I'll have a look what custom labels we are using. Regarding the metrics from `node_exporter`: we probably don't need to used them as the `elasticsearch_exporter` exposes OS metrics from the node endpoint itself.

**Comment by dominikschulz** [comment]
The cluster label is indeed coming from custom tags and relabeling rules. We may want to add a general example how to do this.
