### ISSUE TITLE
filter cache was already renamed in Elasticsearch 2.0

### ISSUE THREAD

**Issue by matsumana** [justwatchcom/elasticsearch_exporter#87]
According to the offical documentation, filter cache was already renamed in 2.0

https://www.elastic.co/guide/en/elasticsearch/reference/2.0/filter-cache.html

> The filter cache has been renamed Node Query Cache

<br>

In 0.90, it seems had `Node Filter Cache` and `Index Filter Cache`.

https://www.elastic.co/guide/en/elasticsearch/reference/0.90/index-modules-cache.html

<br>

I confirmed `GET /_nodes/stats` with 5.5.1 and I got result the following.
In fact, There are no metrics the name of Filter Cache.

```
"query_cache": {
    "memory_size_in_bytes": 14116087,
    "total_count": 3772326,
    "hit_count": 3001713,
    "miss_count": 770613,
    "cache_size": 10870,
    "cache_count": 15374,
    "evictions": 4504
},
"fielddata": {
    "memory_size_in_bytes": 37104,
    "evictions": 0
},
"request_cache": {
    "memory_size_in_bytes": 158617846,
    "evictions": 298639,
    "hit_count": 61328,
    "miss_count": 475752
},
```

<br>

I think that it is better to remove the following, what do you think?

- elasticsearch_indices_filter_cache_evictions
- elasticsearch_indices_filter_cache_memory_size_bytes

If you agree, I'll fix and PR it.
In addition, I would like to add the following.

- elasticsearch_indices_query_cache_hit_rate (hit_count / total_count * 100)
- elasticsearch_indices_query_cache_total_count
- elasticsearch_indices_query_cache_hit_count
- elasticsearch_indices_query_cache_miss_count
- elasticsearch_indices_query_cache_cache_size
- elasticsearch_indices_query_cache_cache_count
- elasticsearch_indices_request_cache_hit_count
- elasticsearch_indices_request_cache_miss_count

**Comment by matsumana** [comment]
Hello, Would you tell me what you think.

**Comment by zwopir** [comment]
Hi Manabu, 

sorry for the late reply. We currently support ES down to version 1.7.6. So removing 
```
elasticsearch_indices_filter_cache_evictions
``` and ```
elasticsearch_indices_filter_cache_memory_size_bytes
```
would break 1.7.6. 

Please refer to the json included inline in the files `./collector/cluster_health_test.go`and `./collector/nodes_test.go` for further details.

We happily accept PRs for missing metrics. For the proposed metrics I suggest some changes:
 
 - `elasticsearch_indices_query_cache_hit_rate (hit_count / total_count * 100)`

please don't include it, it can be calculated via promQL. Also the word 'rate' is misleading as it is usually used in the sense of 'change per time'

For the cache metrics  `elasticsearch_indices_query_cache_total_count`, `elasticsearch_indices_query_cache_hit_count` and `elasticsearch_indices_query_cache_miss_count` (and the similar ones)

I suggest the following metrics instead
 - `elasticsearch_indices_query_cache_total`: type `counter`
 - `elasticsearch_indices_query_cache_count`: type `countervec` with a label `cache` beeing `hit` or `miss`. 

Feel free to find a better label name, as 'cache' is quite generic

**Comment by zwopir** [comment]
#88 resolves one part of the issue, the renaming stays untouched as we support both versions
