### ISSUE TITLE
add documentation for the new metrics

### ISSUE THREAD

**Issue by matsumana** [justwatchcom/elasticsearch_exporter#89]
I want to update README.md about #85 and #88 after #88 will be merged.
so I have a question.

Would you tell me the meaning of cardinality values in README.md?

**Comment by zwopir** [comment]
sure. the cardinality of a metric is the number of metrics you get if you count all possible label-metric combinations. So if you have a metric `foo` with a label `label_foo` and that label can be `value1`, `value2` and `value3` the cardinality of the metric would be 3. If you have multiple labels you simply multiply the numbers of possible label_values of each label. If you are unsure, just add the metric to the README.md and leave the cardinality blank, I can then add the value later on

**Comment by matsumana** [comment]
Thank you. I will send PR.
