### ISSUE TITLE
How to fetch indices names

### ISSUE THREAD

**Issue by niraj8241** [justwatchcom/elasticsearch_exporter#91]
This is not an issue but rather a question to the team.

How do i fetch the name of indices using the elasticsearch_exported. I have properly set it up and i am able to display other metrics which are available. But i do not seem to find any metrics that can display the indices names. My use case is to display it as a table in grafana to view live data ingestion.

**Comment by matsumana** [comment]
Hello.
I added several index metrics few days ago. #85
However, the version containing this PR has not yet been released.

**Comment by zwopir** [comment]
yes, @matsumana created new metrics that can be enabled with `-es.indices`. #85 is in the current master, so its `go get`able if you have go installed. I try to prepare a release candidate today. The indices names are then available the new metrics labels

**Comment by matsumana** [comment]
When will a new version be released?
Could you tell me the schedule.

**Comment by zwopir** [comment]
I try to upload a release candidate on monday

**Comment by zwopir** [comment]
I just released 1.0.2rc1

**Comment by matsumana** [comment]
Thank you
