### ISSUE TITLE
Add support for --version command line parameter

### ISSUE THREAD

**Issue by jklap** [justwatchcom/elasticsearch_exporter#96]
So version can be determined in a manner similar to the official prometheus clients.

It should probably be formatted similar to the official clients also:
* prometheus, version 1.7.2 (branch: HEAD, revision: 22eadbe635528fa17b99a7635fed6b6018103042)

**Comment by zwopir** [comment]
Hi,
sure, we can add such a command line parameter and it makes sense, but it is currently not super high priority - but we happily accept PRs ;)

**Comment by zwopir** [comment]
see #104. We are using single dash comand line parameters though, so the version command is `elasticsearch_exporter -version`.

**Comment by zwopir** [comment]
resolved via #104
