### ISSUE TITLE
Stale cluster health status exposed when `elasticsearch_cluster_health_up` is 0.

### ISSUE THREAD

**Issue by ralphm** [justwatchcom/elasticsearch_exporter#98]
I've run into a case where the ES node being scraped by elasticsearch_exporter went down, but `elasticsearch_cluster_health_status{color="green"}` reported 1, even though `elasticsearch_cluster_health_up` reported 0.

I think what happens is that the last value of the last successful scrape is retained and re-exposed. This seems wrong to me. I expect none of the metrics other than `up`, `total_scrapes` and `json_parse_failures` to be exposed for failed scrapes.

I didn't verify the nodes and indices collectors in detail, but the code pattern looks the same, so I suspect they have the same issue.

**Comment by dominikschulz** [comment]
IMHO the current behavior is correct, i.e. exporting the last known value for any metric.
If you want to monitor the health of your cluster you need to make sure that `elasticsearch_cluster_health_up` is 1.

**Comment by zwopir** [comment]
Hi Ralph,

where did you see the stale metric? `curl`ing the exporter directly or via the prometheus server? Querying the exporter directly shouldn't give you stale metrics, but the prometheus server itself keeps and stale metrics for some time. The default setting for prometheus 1.x servers is 5m, for prometheus 2.x (currently available as a release candidate) it is much shorter. 

The way we create the metrics in the elasticsearch_exporter is similar to https://play.golang.org/p/lqlSr_Hgi8
This test exporter and the elasticsearch_exporter dont export stale metrics, we're not keeping any state of the metrics - they are created on the fly on every call of `Collect()`.

As the `xxxx_up` metrics of the elasticsearch_exporter reflect the success of the http call to the elastic API, you're safe to use it as an indicator for the elasticsearch process health.
