### ISSUE TITLE
Anyway to add custom condition count to metrics 

### ISSUE THREAD

**Issue by VinkDong** [justwatchcom/elasticsearch_exporter#99]
Hi,  Is there any way to add custom metrics which count special query result such as:
```
es_query_count{app="xxx",level="warn",node="node1",...} 10
```
so I can get warning level log quantity at one hour

**Comment by zwopir** [comment]
Hi,

if I understand your question correctly, you want to specify a query and get the result as a metric? Unfortunately there is no possibility to do that. If you like you can elaborate on your use case so we can possibly put it on a feature list.

**Comment by VinkDong** [comment]
@zwopir  
If I define a query as:
```
GET xxx/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "level": "WARN"
          }
        }
      ],
      "filter": {
        "range": {
          "@timestamp": {
            "gte": "now-5m"
          }
        }
      }
    }
  }
}
```
Then we can get result as 
```
{
  "took": 1067,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 8295,
    "max_score": 0.027100416,
    "hits": [
 ...
```
if there is a metrics `es_query_count{app="xxx",level="warn",...} 8295` , I can get every 5 min's WARNING LEVEL data , and display it on grafana via prometheus then config alertmanger rule instead of elastalert.

**Comment by zwopir** [comment]
thanks for elaborating
we already thought about such a feature, but as a separate exporter. But it might be a good idea to integrate it into this exporter. There are a few challenging things with generic queries: 
 - the are potentially executed very often (depending on your number of prometheus servers and scape interval). This makes the exporter a possible culprit to self-DoSing.
 - technically the structure of the query result is unknown to the exporter, so there must be a way to tell the exporter via configuration, where to expect the value to be exported, i.e. some `jq`-style syntax.

so for now there is no solution for your problem, but it's on a "list without milestones"

@tclass: FYI

**Comment by dominikschulz** [comment]
I'm strongly opposed to putting support for this usecase in this exporter. I'd propose to start a separate project to export custom metrics from ES.

**Comment by VinkDong** [comment]
@zwopir @dominikschulz Thanks, now I think  I need to start a new project for my case
